import type { Phrase } from './types';

/** The signed-in member area: account, autoship, team, orders, wallet, recharge, statements, support. */
export const MEMBER: Phrase[] = [
  // account
  ['Lifetime', 'आजीवन', 'আজীবন'],
  ['Waiting on us', 'हमारी ओर से प्रतीक्षित', 'আমাদের দিক থেকে অপেক্ষমাণ'],
  ['being checked ·', 'जाँच में ·', 'যাচাই চলছে ·'],
  ['See', 'देखें', 'দেখুন'],
  ['being processed ·', 'प्रक्रिया में ·', 'প্রক্রিয়াধীন ·'],
  ['Your own purchases', 'आपकी अपनी खरीदारी', 'আপনার নিজের কেনাকাটা'],
  ['You and your team', 'आप और आपकी टीम', 'আপনি ও আপনার টিম'],
  ['Your details', 'आपका विवरण', 'আপনার বিবরণ'],
  ['Name', 'नाम', 'নাম'],
  ['Member ID', 'सदस्य आईडी', 'সদস্য আইডি'],
  ['Mobile', 'मोबाइल', 'মোবাইল'],
  ['Not added', 'जोड़ा नहीं गया', 'যোগ করা হয়নি'],
  ['Payout details', 'पेआउट विवरण', 'পেআউট বিবরণ'],
  ['Change', 'बदलें', 'বদলান'],
  ['Add', 'जोड़ें', 'যোগ করুন'],
  ['Bank', 'बैंक', 'ব্যাংক'],
  ['Account holder', 'खाताधारक', 'অ্যাকাউন্টধারী'],
  ['UPI ID', 'UPI आईडी', 'UPI আইডি'],
  ['e.g. yourname@bank — the quickest route', 'जैसे yourname@bank — सबसे तेज़ तरीका', 'যেমন yourname@bank — দ্রুততম উপায়'],
  ['Account number', 'खाता संख्या', 'অ্যাকাউন্ট নম্বর'],
  ['Saving…', 'सहेजा जा रहा है…', 'সংরক্ষণ হচ্ছে…'],
  ['Save', 'सहेजें', 'সংরক্ষণ করুন'],
  ['No payout details yet. Add them before you request a withdrawal.', 'अभी कोई पेआउट विवरण नहीं है। निकासी का अनुरोध करने से पहले जोड़ें।', 'এখনও কোনো পেআউট বিবরণ নেই। টাকা তোলার অনুরোধের আগে যোগ করুন।'],
  ['Or a bank account', 'या बैंक खाता', 'অথবা একটি ব্যাংক অ্যাকাউন্ট'],
  ['Cancel', 'रद्द करें', 'বাতিল করুন'],
  ['Messages on your phone', 'आपके फ़ोन पर संदेश', 'আপনার ফোনে বার্তা'],
  ['SMS and WhatsApp when an order ships, money reaches your wallet or a withdrawal is paid.', 'ऑर्डर शिप होने, वॉलेट में पैसे आने या निकासी का भुगतान होने पर SMS और WhatsApp।', 'অর্ডার শিপ হলে, ওয়ালেটে টাকা এলে বা টাকা তোলার পেমেন্ট হলে SMS ও WhatsApp।'],
  ['Could not save that. Try again.', 'यह सहेजा नहीं जा सका। फिर कोशिश करें।', 'এটি সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।'],
  ['SMS and WhatsApp messages', 'SMS और WhatsApp संदेश', 'SMS ও WhatsApp বার্তা'],
  ['Where income withdrawals are sent. Must be an account in your own name.', 'आय की निकासी यहाँ भेजी जाती है। यह आपके अपने नाम का खाता होना चाहिए।', 'আয়ের উত্তোলন এখানে পাঠানো হয়। অবশ্যই আপনার নিজের নামের অ্যাকাউন্ট হতে হবে।'],
  ['Payouts are only made to an account in the member’s own name. An account that already belongs to another member will be refused.', 'पेआउट केवल सदस्य के अपने नाम के खाते में किया जाता है। जो खाता पहले से किसी अन्य सदस्य का है उसे अस्वीकार कर दिया जाएगा।', 'পেআউট শুধু সদস্যের নিজের নামের অ্যাকাউন্টে করা হয়। যে অ্যাকাউন্ট ইতিমধ্যে অন্য সদস্যের তা প্রত্যাখ্যান করা হবে।'],
  ['Your account is on hold, so new orders and withdrawals are paused. Contact customer care to sort it out.', 'आपका खाता होल्ड पर है, इसलिए नए ऑर्डर और निकासी रुकी हुई हैं। इसे ठीक कराने के लिए ग्राहक सेवा से संपर्क करें।', 'আপনার অ্যাকাউন্ট হোল্ডে আছে, তাই নতুন অর্ডার ও উত্তোলন বন্ধ। সমাধানের জন্য গ্রাহক সেবার সঙ্গে যোগাযোগ করুন।'],
  // autoship
  ['Autoship', 'ऑटोशिप', 'অটোশিপ'],
  ['Paused', 'रुका हुआ', 'বিরতিতে'],
  ['This order alone meets your monthly target.', 'यह ऑर्डर अकेले ही आपका मासिक लक्ष्य पूरा करता है।', 'এই অর্ডারটিই আপনার মাসিক লক্ষ্য পূরণ করে।'],
  ['Pause', 'रोकें', 'বিরতি দিন'],
  ['Resume', 'फिर शुरू करें', 'আবার শুরু করুন'],
  ['Remove your autoship order?', 'अपना ऑटोशिप ऑर्डर हटाएँ?', 'আপনার অটোশিপ অর্ডার সরাবেন?'],
  ['Your monthly order', 'आपका मासिक ऑर्डर', 'আপনার মাসিক অর্ডার'],
  ['About', 'लगभग', 'প্রায়'],
  ['Next order:', 'अगला ऑर्डर:', 'পরের অর্ডার:'],
  ['Last run:', 'पिछली बार:', 'শেষবার:'],
  ['Remove', 'हटाएँ', 'সরান'],
  ['Change your monthly order', 'अपना मासिक ऑर्डर बदलें', 'আপনার মাসিক অর্ডার বদলান'],
  ['Set up your monthly order', 'अपना मासिक ऑर्डर सेट करें', 'আপনার মাসিক অর্ডার সেট করুন'],
  ['Product to add', 'जोड़ने के लिए उत्पाद', 'যোগ করার পণ্য'],
  ['Product', 'उत्पाद', 'পণ্য'],
  ['Fewer', 'कम', 'কম'],
  ['More', 'ज़्यादा', 'বেশি'],
  ['- meets your monthly target.', '- आपका मासिक लक्ष्य पूरा करता है।', '- আপনার মাসিক লক্ষ্য পূরণ করে।'],
  ['Save autoship', 'ऑटोशिप सहेजें', 'অটোশিপ সংরক্ষণ করুন'],
  ['Choose a product…', 'कोई उत्पाद चुनें…', 'একটি পণ্য বেছে নিন…'],
  ['Order on the', 'ऑर्डर तारीख:', 'অর্ডারের তারিখ:'],
  ['of every month', 'हर महीने की', 'প্রতি মাসের'],
  ['Pick what you buy every month and the day you want it. On that day the order is placed from your shopping wallet, exactly like an order you place yourself - so it counts toward your monthly target{targetClause}. If your wallet is short, nothing is charged and we let you know.', 'चुनें कि हर महीने क्या खरीदना है और किस दिन। उस दिन ऑर्डर आपके शॉपिंग वॉलेट से दिया जाता है, बिल्कुल आपके अपने ऑर्डर की तरह - इसलिए यह आपके मासिक लक्ष्य{targetClause} में गिना जाता है। वॉलेट में कमी हो तो कुछ नहीं कटता और हम आपको बताते हैं।', 'প্রতি মাসে কী কিনবেন ও কোন দিনে তা বেছে নিন। সেই দিন অর্ডারটি আপনার শপিং ওয়ালেট থেকে দেওয়া হয়, ঠিক আপনার নিজের অর্ডারের মতো - তাই এটি আপনার মাসিক লক্ষ্যে{targetClause} গণ্য হয়। ওয়ালেটে ঘাটতি থাকলে কিছু কাটা হয় না এবং আমরা আপনাকে জানাই।'],
  ['Delivered to your saved address. Prices include GST; the order is priced on the day. Add money to your shopping wallet before the day so the order can be paid.', 'आपके सहेजे गए पते पर डिलीवर। कीमतों में GST शामिल है; ऑर्डर की कीमत उसी दिन तय होती है। भुगतान हो सके इसलिए उस दिन से पहले अपने शॉपिंग वॉलेट में पैसे जोड़ें।', 'আপনার সংরক্ষিত ঠিকানায় ডেলিভারি। দামে GST অন্তর্ভুক্ত; অর্ডারের দাম সেই দিনেই ঠিক হয়। পেমেন্ট হতে পারে তাই সেই দিনের আগে আপনার শপিং ওয়ালেটে টাকা যোগ করুন।'],
  // team
  ['Joined', 'जुड़े', 'যোগ দিয়েছেন'],
  ['No one below yet.', 'अभी नीचे कोई नहीं।', 'এখনও নিচে কেউ নেই।'],
  ['Target met', 'लक्ष्य पूरा', 'লক্ষ্য পূরণ'],
  ['Below target', 'लक्ष्य से नीचे', 'লক্ষ্যের নিচে'],
  ['My team', 'मेरी टीम', 'আমার টিম'],
  ['Direct', 'सीधे', 'সরাসরি'],
  ['People you sponsored yourself', 'वे लोग जिन्हें आपने स्वयं स्पॉन्सर किया', 'যাঁদের আপনি নিজে স্পনসর করেছেন'],
  ['Total team', 'कुल टीम', 'মোট টিম'],
  ['Everyone below you, to ten levels', 'आपके नीचे सभी, दस स्तर तक', 'আপনার নিচে সবাই, দশ স্তর পর্যন্ত'],
  ['Active', 'सक्रिय', 'সক্রিয়'],
  ['Accounts currently in good standing', 'वे खाते जो अभी अच्छी स्थिति में हैं', 'যে অ্যাকাউন্টগুলি এখন ভালো অবস্থায় আছে'],
  ['By level', 'स्तर के अनुसार', 'স্তর অনুযায়ী'],
  ['Level', 'स्तर', 'স্তর'],
  ['Find someone in your team', 'अपनी टीम में किसी को खोजें', 'আপনার টিমে কাউকে খুঁজুন'],
  ['First name or member ID', 'पहला नाम या सदस्य आईडी', 'প্রথম নাম বা সদস্য আইডি'],
  ['Member', 'सदस्य', 'সদস্য'],
  ['Searching…', 'खोजा जा रहा है…', 'খোঁজা হচ্ছে…'],
  ['· This month', '· इस महीने', '· এই মাসে'],
  ['No one in your team matches “', 'आपकी टीम में कोई मेल नहीं खाता “', 'আপনার টিমে কেউ মেলে না “'],
  ['People you sponsored', 'वे लोग जिन्हें आपने स्पॉन्सर किया', 'যাঁদের আপনি স্পনসর করেছেন'],
  ['Showing below target', 'लक्ष्य से नीचे वाले दिखा रहे हैं', 'লক্ষ্যের নিচেরগুলি দেখানো হচ্ছে'],
  ['Show only below target', 'केवल लक्ष्य से नीचे वाले दिखाएँ', 'শুধু লক্ষ্যের নিচেরগুলি দেখান'],
  ["This month's target is", 'इस महीने का लक्ष्य है', 'এই মাসের লক্ষ্য'],
  ['of purchases:', 'खरीदारी का:', 'কেনাকাটার:'],
  ['Everyone has met the target', 'सभी ने लक्ष्य पूरा कर लिया', 'সবাই লক্ষ্য পূরণ করেছেন'],
  ["Nobody in your direct team is below this month's target.", 'आपकी सीधी टीम में कोई भी इस महीने के लक्ष्य से नीचे नहीं है।', 'আপনার সরাসরি টিমে কেউ এই মাসের লক্ষ্যের নিচে নেই।'],
  ['You', 'आप', 'আপনি'],
  ['Showing the most recent 100. Use the team report in your account for the full list.', 'सबसे हाल के 100 दिखा रहे हैं। पूरी सूची के लिए अपने खाते में टीम रिपोर्ट इस्तेमाल करें।', 'সাম্প্রতিক ১০০টি দেখানো হচ্ছে। পুরো তালিকার জন্য আপনার অ্যাকাউন্টের টিম রিপোর্ট ব্যবহার করুন।'],
  ['Invite someone', 'किसी को आमंत्रित करें', 'কাউকে আমন্ত্রণ জানান'],
  ['Your member ID', 'आपकी सदस्य आईडी', 'আপনার সদস্য আইডি'],
  ['Copied', 'कॉपी हो गया', 'কপি হয়েছে'],
  ['Copy', 'कॉपी करें', 'কপি করুন'],
  ['Referral link', 'रेफ़रल लिंक', 'রেফারেল লিঙ্ক'],
  ['Your storefront', 'आपका स्टोरफ्रंट', 'আপনার স্টোরফ্রন্ট'],
  ['The code is remembered when someone opens your link, even though it disappears from the address bar.', 'जब कोई आपका लिंक खोलता है तो कोड याद रखा जाता है, भले ही वह एड्रेस बार से गायब हो जाए।', 'কেউ আপনার লিঙ্ক খুললে কোডটি মনে রাখা হয়, যদিও তা অ্যাড্রেস বার থেকে মিলিয়ে যায়।'],
  ['Level 1 is the people you sponsored. Level 2 is the people they sponsored, and so on.', 'स्तर 1 वे लोग हैं जिन्हें आपने स्पॉन्सर किया। स्तर 2 वे हैं जिन्हें उन्होंने स्पॉन्सर किया, और इसी तरह आगे।', 'স্তর ১ হলেন যাঁদের আপনি স্পনসর করেছেন। স্তর ২ হলেন যাঁদের তাঁরা স্পনসর করেছেন, এভাবে চলে।'],
  ['Nobody yet', 'अभी तक कोई नहीं', 'এখনও কেউ নেই'],
  ['Share your referral link with anyone who wants to sell the products. They will appear here once they sign up.', 'अपना रेफ़रल लिंक उन सभी के साथ साझा करें जो उत्पाद बेचना चाहते हैं। साइन अप करने के बाद वे यहाँ दिखेंगे।', 'যাঁরা পণ্য বিক্রি করতে চান তাঁদের সঙ্গে আপনার রেফারেল লিঙ্ক শেয়ার করুন। সাইন আপ করার পর তাঁরা এখানে দেখা যাবে।'],
  ['Earnings are not shown here — neither yours nor anyone else’s. Your own income is in your wallet statement; what the people in your team earn is theirs to share or not.', 'कमाई यहाँ नहीं दिखाई जाती — न आपकी, न किसी और की। आपकी अपनी आय आपके वॉलेट स्टेटमेंट में है; आपकी टीम के लोग क्या कमाते हैं यह बताना उनकी मर्ज़ी है।', 'আয় এখানে দেখানো হয় না — না আপনার, না অন্য কারও। আপনার নিজের আয় ওয়ালেট স্টেটমেন্টে আছে; আপনার টিমের লোকেরা কত আয় করেন তা জানানো তাঁদের ইচ্ছা।'],
  ['Anyone who signs up through your link or with your ID joins your team. Joining is free.', 'जो भी आपके लिंक से या आपकी आईडी से साइन अप करता है वह आपकी टीम में जुड़ता है। जुड़ना मुफ़्त है।', 'যিনিই আপনার লিঙ্ক বা আইডি দিয়ে সাইন আপ করেন তিনি আপনার টিমে যোগ দেন। যোগ দেওয়া বিনামূল্যে।'],
  ['A full page with your name on it, not just a tracked link — better for a WhatsApp status or a bio link.', 'आपके नाम वाला पूरा पेज, सिर्फ़ एक ट्रैक किया गया लिंक नहीं — WhatsApp स्टेटस या बायो लिंक के लिए बेहतर।', 'আপনার নাম সহ একটি পূর্ণ পেজ, শুধু ট্র্যাক করা লিঙ্ক নয় — WhatsApp স্ট্যাটাস বা বায়ো লিঙ্কের জন্য ভালো।'],
  ['Join Majestic Cart and shop with me — sign up with my ID {code}', 'Majestic Cart से जुड़ें और मेरे साथ खरीदारी करें — मेरी आईडी {code} से साइन अप करें', 'Majestic Cart-এ যোগ দিন ও আমার সঙ্গে কেনাকাটা করুন — আমার আইডি {code} দিয়ে সাইন আপ করুন'],
  // orders
  ['Order', 'ऑर्डर', 'অর্ডার'],
  ['← All orders', '← सभी ऑर्डर', '← সব অর্ডার'],
  ['Order placed', 'ऑर्डर दिया गया', 'অর্ডার দেওয়া হয়েছে'],
  ['Paid from your shopping wallet. We will let you know when it ships.', 'आपके शॉपिंग वॉलेट से भुगतान हुआ। शिप होने पर हम आपको बताएँगे।', 'আপনার শপিং ওয়ালেট থেকে পেমেন্ট হয়েছে। শিপ হলে আমরা জানাব।'],
  ['Placed', 'दिया गया', 'দেওয়া হয়েছে'],
  ['Download invoice', 'इनवॉइस डाउनलोड करें', 'ইনভয়েস ডাউনলোড করুন'],
  ['The GST invoice is issued when the order is delivered.', 'GST इनवॉइस ऑर्डर डिलीवर होने पर जारी किया जाता है।', 'অর্ডার ডেলিভারি হলে GST ইনভয়েস দেওয়া হয়।'],
  ['Progress', 'प्रगति', 'অগ্রগতি'],
  ['Items', 'आइटम', 'আইটেম'],
  ['Paid from wallet', 'वॉलेट से भुगतान', 'ওয়ালেট থেকে পেমেন্ট'],
  ['of which GST', 'जिसमें GST', 'যার মধ্যে GST'],
  ['Cancelling…', 'रद्द किया जा रहा है…', 'বাতিল হচ্ছে…'],
  ['Cancel order', 'ऑर्डर रद्द करें', 'অর্ডার বাতিল করুন'],
  ['The amount goes back to your shopping wallet.', 'राशि आपके शॉपिंग वॉलेट में वापस चली जाती है।', 'টাকা আপনার শপিং ওয়ালেটে ফিরে যায়।'],
  ['Orders', 'ऑर्डर', 'অর্ডার'],
  ['No orders yet', 'अभी तक कोई ऑर्डर नहीं', 'এখনও কোনো অর্ডার নেই'],
  ['Invoice', 'इनवॉइस', 'ইনভয়েস'],
  ['Could not load more orders.', 'और ऑर्डर लोड नहीं हो सके।', 'আরও অর্ডার লোড করা যায়নি।'],
  ['Loading…', 'लोड हो रहा है…', 'লোড হচ্ছে…'],
  ['Load more', 'और लोड करें', 'আরও লোড করুন'],
  ['View order →', 'ऑर्डर देखें →', 'অর্ডার দেখুন →'],
  // reviews
  ['Reviews', 'समीक्षाएँ', 'রিভিউ'],
  ['Verified purchase', 'सत्यापित खरीदारी', 'যাচাই করা কেনাকাটা'],
  ['Show more reviews', 'और समीक्षाएँ दिखाएँ', 'আরও রিভিউ দেখান'],
  ['No reviews yet.', 'अभी कोई समीक्षा नहीं।', 'এখনও কোনো রিভিউ নেই।'],
  ['Edit your review', 'अपनी समीक्षा संपादित करें', 'আপনার রিভিউ সম্পাদনা করুন'],
  ['Write a review', 'समीक्षा लिखें', 'রিভিউ লিখুন'],
  ['to review a product you have received.', 'प्राप्त हुए उत्पाद की समीक्षा करने के लिए।', 'পেয়ে যাওয়া পণ্যের রিভিউ করতে।'],
  ['You can review this product once an order with it has been delivered to you.', 'इस उत्पाद वाला ऑर्डर आपको डिलीवर होने के बाद आप इसकी समीक्षा कर सकते हैं।', 'এই পণ্যসহ অর্ডার আপনাকে ডেলিভারি হওয়ার পর আপনি এর রিভিউ করতে পারবেন।'],
  ['Your review is not showing right now - it is being looked at by our team.', 'आपकी समीक्षा अभी दिख नहीं रही - हमारी टीम उसे देख रही है।', 'আপনার রিভিউ এখন দেখা যাচ্ছে না - আমাদের টিম এটি দেখছে।'],
  ['Your rating', 'आपकी रेटिंग', 'আপনার রেটিং'],
  ['Star rating', 'स्टार रेटिंग', 'স্টার রেটিং'],
  ['Headline (optional)', 'शीर्षक (वैकल्पिक)', 'শিরোনাম (ঐচ্ছিক)'],
  ['What did you like, or not? How did you use it?', 'आपको क्या पसंद आया, या नहीं? आपने इसे कैसे इस्तेमाल किया?', 'আপনার কী ভালো লেগেছে বা লাগেনি? কীভাবে ব্যবহার করেছেন?'],
  ['Post review', 'समीक्षा पोस्ट करें', 'রিভিউ পোস্ট করুন'],
  // rank
  ['Current rank', 'वर्तमान रैंक', 'বর্তমান র‍্যাঙ্ক'],
  ['Member since', 'सदस्य बने', 'সদস্য হয়েছেন'],
  ['Counted on your team’s purchases, not your own.', 'आपकी टीम की खरीदारी पर गिना जाता है, आपकी अपनी पर नहीं।', 'আপনার টিমের কেনাকাটায় গণনা হয়, আপনার নিজের নয়।'],
  ['Counted on your own and your whole team’s purchases.', 'आपकी अपनी और पूरी टीम की खरीदारी पर गिना जाता है।', 'আপনার নিজের ও পুরো টিমের কেনাকাটায় গণনা হয়।'],
  ['to go', 'बाकी', 'বাকি'],
  ['% of the way there.', '% रास्ता तय हो चुका।', '% পথ পেরিয়েছে।'],
  ['You have', 'आपके पास है', 'আপনার আছে'],
  ['Still needed', 'अभी भी चाहिए', 'এখনও দরকার'],
  ['What', 'क्या', 'কী'],
  ['on your purchases', 'आपकी खरीदारी पर', 'আপনার কেনাকাটায়'],
  ['You are at the top rank. Nothing left to climb.', 'आप सबसे ऊँचे रैंक पर हैं। चढ़ने को कुछ नहीं बचा।', 'আপনি সর্বোচ্চ র‍্যাঙ্কে আছেন। ওঠার আর কিছু নেই।'],
  ['You reached', 'आप पहुँचे', 'আপনি পৌঁছেছেন'],
  ['Your new rate applies to commission earned from here on. Income already credited stays as it was paid.', 'आपकी नई दर अब से कमाए गए कमीशन पर लागू होती है। जो आय पहले ही जमा हो चुकी है वह जैसी दी गई थी वैसी रहती है।', 'আপনার নতুন হার এখন থেকে অর্জিত কমিশনে প্রযোজ্য। যে আয় ইতিমধ্যে জমা হয়েছে তা যেমন দেওয়া হয়েছিল তেমনই থাকে।'],
  ['Dismiss', 'हटाएँ', 'বন্ধ করুন'],
  // recharge
  ['Submitted for approval', 'अनुमोदन के लिए जमा किया गया', 'অনুমোদনের জন্য জমা দেওয়া হয়েছে'],
  ['Our team will check the payment against the bank statement and credit your wallet. Most are done within a few working hours. You will get a notification either way.', 'हमारी टीम भुगतान को बैंक स्टेटमेंट से मिलाकर आपके वॉलेट में जमा करेगी। ज़्यादातर कुछ कार्य-घंटों में हो जाते हैं। आपको किसी भी स्थिति में सूचना मिलेगी।', 'আমাদের টিম ব্যাংক স্টেটমেন্টের সঙ্গে পেমেন্ট মিলিয়ে আপনার ওয়ালেটে জমা করবে। বেশিরভাগ কয়েক কার্যঘণ্টার মধ্যে হয়ে যায়। যেকোনো ক্ষেত্রে আপনি বিজ্ঞপ্তি পাবেন।'],
  ['Your bag is still waiting.', 'आपका बैग अभी भी इंतज़ार कर रहा है।', 'আপনার ব্যাগ এখনও অপেক্ষা করছে।'],
  ['Back to checkout →', 'चेकआउट पर वापस →', 'চেকআউটে ফিরে যান →'],
  ['A request is being checked', 'एक अनुरोध की जाँच हो रही है', 'একটি অনুরোধ যাচাই হচ্ছে'],
  ['· UTR', '· UTR', '· UTR'],
  ['Nothing has been deducted twice — a pending request is a payment we have not yet matched to the bank statement. You can still submit another for a different payment.', 'कुछ भी दो बार नहीं कटा — लंबित अनुरोध वह भुगतान है जिसे हमने अभी बैंक स्टेटमेंट से नहीं मिलाया। आप किसी अलग भुगतान के लिए दूसरा जमा कर सकते हैं।', 'কিছু দুবার কাটা হয়নি — মুলতুবি অনুরোধ মানে এমন পেমেন্ট যা আমরা এখনও ব্যাংক স্টেটমেন্টের সঙ্গে মেলাইনি। ভিন্ন পেমেন্টের জন্য আপনি আরেকটি জমা দিতে পারেন।'],
  ['1. Pay by UPI', '1. UPI से भुगतान करें', '১. UPI-তে পেমেন্ট করুন'],
  ['Scan this with any UPI app, or copy the ID below.', 'इसे किसी भी UPI ऐप से स्कैन करें, या नीचे दी गई आईडी कॉपी करें।', 'যেকোনো UPI অ্যাপ দিয়ে এটি স্ক্যান করুন, বা নিচের আইডি কপি করুন।'],
  ['Pay between', 'इनके बीच भुगतान करें:', 'এর মধ্যে পেমেন্ট করুন:'],
  ['in one transfer.', 'एक ही ट्रांसफ़र में।', 'এক ট্রান্সফারে।'],
  ['Payment details are unavailable right now. Please try again shortly.', 'भुगतान का विवरण अभी उपलब्ध नहीं है। कृपया थोड़ी देर बाद फिर कोशिश करें।', 'পেমেন্টের বিবরণ এখন পাওয়া যাচ্ছে না। অনুগ্রহ করে একটু পরে আবার চেষ্টা করুন।'],
  ['2. Tell us about it', '2. हमें इसके बारे में बताएँ', '২. আমাদের জানান'],
  ['So we can match your payment to your account.', 'ताकि हम आपके भुगतान को आपके खाते से मिला सकें।', 'যাতে আমরা আপনার পেমেন্ট আপনার অ্যাকাউন্টের সঙ্গে মেলাতে পারি।'],
  ['Amount paid', 'भुगतान की गई राशि', 'পরিশোধিত পরিমাণ'],
  ['Pre-filled with what your bag needs. You can add more.', 'आपके बैग की ज़रूरत के हिसाब से पहले से भरा है। आप ज़्यादा जोड़ सकते हैं।', 'আপনার ব্যাগের প্রয়োজন অনুযায়ী আগে থেকে পূরণ করা। আপনি আরও যোগ করতে পারেন।'],
  ['UTR / reference number', 'UTR / संदर्भ संख्या', 'UTR / রেফারেন্স নম্বর'],
  ['In your UPI app, open the payment and look for', 'अपने UPI ऐप में भुगतान खोलें और देखें:', 'আপনার UPI অ্যাপে পেমেন্টটি খুলে দেখুন:'],
  ['UPI transaction ID', 'UPI ट्रांज़ैक्शन आईडी', 'UPI ট্রানজ্যাকশন আইডি'],
  ['Reference number', 'संदर्भ संख्या', 'রেফারেন্স নম্বর'],
  ['. It is 12 digits or more.', '. यह 12 या अधिक अंकों का होता है।', '. এটি ১২ বা তার বেশি সংখ্যার।'],
  ['Payment screenshot', 'भुगतान का स्क्रीनशॉट', 'পেমেন্টের স্ক্রিনশট'],
  ['Submit for approval', 'अनुमोदन के लिए जमा करें', 'অনুমোদনের জন্য জমা দিন'],
  ['Your wallet is credited after our team matches this payment to the bank statement. It is not instant.', 'हमारी टीम द्वारा इस भुगतान को बैंक स्टेटमेंट से मिलाने के बाद आपका वॉलेट जमा होता है। यह तुरंत नहीं होता।', 'আমাদের টিম এই পেমেন্ট ব্যাংক স্টেটমেন্টের সঙ্গে মেলানোর পর আপনার ওয়ালেট জমা হয়। এটি তাৎক্ষণিক নয়।'],
  ['Recent requests', 'हाल के अनुरोध', 'সাম্প্রতিক অনুরোধ'],
  ['Shopping wallet balance:', 'शॉपिंग वॉलेट बैलेंस:', 'শপিং ওয়ালেটের ব্যালেন্স:'],
  ['No requests yet', 'अभी कोई अनुरोध नहीं', 'এখনও কোনো অনুরোধ নেই'],
  ['Once you submit a payment it will appear here with its status.', 'भुगतान जमा करने के बाद वह अपनी स्थिति के साथ यहाँ दिखेगा।', 'পেমেন্ট জমা দেওয়ার পর তা স্ট্যাটাস সহ এখানে দেখা যাবে।'],
  // shade finder / share
  ['AI shade finder', 'AI शेड फ़ाइंडर', 'AI শেড ফাইন্ডার'],
  ['Find your shade', 'अपना शेड खोजें', 'আপনার শেড খুঁজুন'],
  ['Analysing…', 'विश्लेषण हो रहा है…', 'বিশ্লেষণ চলছে…'],
  ['Find my shade', 'मेरा शेड खोजें', 'আমার শেড খুঁজুন'],
  ['Take or upload a selfie', 'सेल्फ़ी लें या अपलोड करें', 'সেলফি তুলুন বা আপলোড করুন'],
  ['JPEG, PNG or WEBP', 'JPEG, PNG या WEBP', 'JPEG, PNG বা WEBP'],
  ['Choose another', 'दूसरी चुनें', 'আরেকটি বেছে নিন'],
  ['Nothing in the current makeup range matched well — worth browsing', 'मौजूदा मेकअप रेंज में कुछ भी अच्छी तरह मेल नहीं खाया — देखने लायक है', 'বর্তমান মেকআপ সংগ্রহে কিছুই ভালোভাবে মেলেনি — ঘুরে দেখার মতো'],
  ['the full range', 'पूरी रेंज', 'পুরো সংগ্রহ'],
  ['Try another photo →', 'दूसरी फ़ोटो आज़माएँ →', 'আরেকটি ছবি চেষ্টা করুন →'],
  ['A clear photo in good light — front-facing, no filter — works best.', 'अच्छी रोशनी में साफ़ फ़ोटो — सामने से, बिना फ़िल्टर — सबसे अच्छा काम करती है।', 'ভালো আলোয় পরিষ্কার ছবি — সামনে থেকে, ফিল্টার ছাড়া — সবচেয়ে ভালো কাজ করে।'],
  ['Your photo is analysed and then discarded; it is never saved.', 'आपकी फ़ोटो का विश्लेषण होता है और फिर हटा दी जाती है; उसे कभी सहेजा नहीं जाता।', 'আপনার ছবি বিশ্লেষণ করে মুছে ফেলা হয়; কখনও সংরক্ষণ করা হয় না।'],
  ['Share', 'शेयर करें', 'শেয়ার করুন'],
  ['WhatsApp messages', 'WhatsApp संदेश', 'WhatsApp বার্তা'],
  ['Ready to send. Each one carries your storefront link.', 'भेजने के लिए तैयार। हर एक में आपका स्टोरफ्रंट लिंक है।', 'পাঠানোর জন্য প্রস্তুত। প্রতিটিতে আপনার স্টোরফ্রন্ট লিঙ্ক আছে।'],
  ['Copy message', 'संदेश कॉपी करें', 'বার্তা কপি করুন'],
  ['Send on WhatsApp', 'WhatsApp पर भेजें', 'WhatsApp-এ পাঠান'],
  ['These messages talk about the products and free registration only. Please do not add claims about earnings or promise anyone income - it is against the direct selling rules and against your agreement with us.', 'ये संदेश केवल उत्पादों और मुफ़्त पंजीकरण के बारे में हैं। कृपया कमाई के दावे न जोड़ें और किसी को आय का वादा न करें - यह डायरेक्ट सेलिंग नियमों के और हमारे साथ आपके समझौते के विरुद्ध है।', 'এই বার্তাগুলি শুধু পণ্য ও বিনামূল্যে নিবন্ধন নিয়ে। অনুগ্রহ করে আয়ের দাবি যোগ করবেন না বা কাউকে আয়ের প্রতিশ্রুতি দেবেন না - এটি ডাইরেক্ট সেলিং নিয়মের এবং আমাদের সঙ্গে আপনার চুক্তির পরিপন্থী।'],
  ['Share image', 'इमेज शेयर करें', 'ছবি শেয়ার করুন'],
  ['Preparing…', 'तैयार हो रहा है…', 'প্রস্তুত হচ্ছে…'],
  ['Download image', 'इमेज डाउनलोड करें', 'ছবি ডাউনলোড করুন'],
  ['Share…', 'शेयर करें…', 'শেয়ার করুন…'],
  // statement
  ['Income statement', 'इनकम स्टेटमेंट', 'ইনকাম স্টেটমেন্ট'],
  ['Month', 'महीना', 'মাস'],
  ['Download PDF', 'PDF डाउनलोड करें', 'PDF ডাউনলোড করুন'],
  ['Income earned in', 'इसमें अर्जित आय:', 'এতে অর্জিত আয়:'],
  ['Total income', 'कुल आय', 'মোট আয়'],
  ['Withdrawals and deduction (TDS)', 'निकासी और कटौती (TDS)', 'উত্তোলন ও কর্তন (TDS)'],
  ['No withdrawals were requested this month.', 'इस महीने कोई निकासी अनुरोध नहीं किया गया।', 'এই মাসে কোনো উত্তোলনের অনুরোধ করা হয়নি।'],
  ['Date', 'तारीख', 'তারিখ'],
  ['Requested', 'अनुरोध किया', 'অনুরোধ করা'],
  ['Deduction', 'कटौती', 'কর্তন'],
  ['Paid to you', 'आपको भुगतान', 'আপনাকে পেমেন্ট'],
  ['Status', 'स्थिति', 'স্ট্যাটাস'],
  ['Income wallet, start of month', 'इनकम वॉलेट, महीने की शुरुआत', 'ইনকাম ওয়ালেট, মাসের শুরু'],
  ['Income wallet, end of month', 'इनकम वॉलेट, महीने का अंत', 'ইনকাম ওয়ালেট, মাসের শেষ'],
  ['Rejected withdrawals are returned to your wallet and are not counted in the totals.', 'अस्वीकृत निकासी आपके वॉलेट में लौटा दी जाती है और कुल में नहीं गिनी जाती।', 'প্রত্যাখ্যাত উত্তোলন আপনার ওয়ালেটে ফেরত যায় এবং মোটে গণনা হয় না।'],
  // support
  ['Support', 'सहायता', 'সাপোর্ট'],
  ['New ticket', 'नया टिकट', 'নতুন টিকিট'],
  ['You have no tickets.', 'आपका कोई टिकट नहीं है।', 'আপনার কোনো টিকিট নেই।'],
  ['What happened? Include an order number if there is one.', 'क्या हुआ? यदि ऑर्डर नंबर है तो शामिल करें।', 'কী হয়েছে? অর্ডার নম্বর থাকলে উল্লেখ করুন।'],
  ['Send', 'भेजें', 'পাঠান'],
  ['Majestic Cart', 'Majestic Cart', 'Majestic Cart'],
  ['We will acknowledge this by', 'हम इसे इस तक स्वीकार करेंगे:', 'আমরা এটি এর মধ্যে স্বীকার করব:'],
  ['Reply to re-open', 'दोबारा खोलने के लिए जवाब दें', 'আবার খুলতে উত্তর দিন'],
  ['Add a reply', 'जवाब जोड़ें', 'উত্তর যোগ করুন'],
  ['Reply', 'जवाब दें', 'উত্তর দিন'],
  ['Ask a question or raise a complaint. We acknowledge every ticket within 48 hours and aim to resolve it within a month.', 'कोई सवाल पूछें या शिकायत दर्ज करें। हम हर टिकट को 48 घंटे में स्वीकार करते हैं और एक महीने में सुलझाने का लक्ष्य रखते हैं।', 'প্রশ্ন করুন বা অভিযোগ জানান। আমরা প্রতিটি টিকিট ৪৮ ঘণ্টার মধ্যে স্বীকার করি এবং এক মাসের মধ্যে সমাধানের লক্ষ্য রাখি।'],
  // wallet
  ['Add money', 'पैसे जोड़ें', 'টাকা যোগ করুন'],
  ['Recharge mobile instead', 'इसके बजाय मोबाइल रिचार्ज करें', 'এর বদলে মোবাইল রিচার্জ করুন'],
  ['Income wallet', 'इनकम वॉलेट', 'ইনকাম ওয়ালেট'],
  ['Withdraw', 'निकासी', 'উত্তোলন'],
  ['See statement →', 'स्टेटमेंट देखें →', 'স্টেটমেন্ট দেখুন →'],
  ['Nothing here yet', 'अभी यहाँ कुछ नहीं', 'এখনও এখানে কিছু নেই'],
  ['Shopping', 'शॉपिंग', 'শপিং'],
  ['Income', 'आय', 'আয়'],
  ['Balance', 'बैलेंस', 'ব্যালেন্স'],
  ['Funded by UPI payments you submit for approval. Spends on orders — or on a mobile recharge, if you’d rather not shop right now. Cannot be withdrawn as cash.', 'आपके अनुमोदन के लिए जमा किए UPI भुगतानों से भरा जाता है। ऑर्डर पर खर्च होता है — या मोबाइल रिचार्ज पर, यदि आप अभी खरीदारी नहीं करना चाहते। नकद के रूप में निकाला नहीं जा सकता।', 'অনুমোদনের জন্য জমা দেওয়া UPI পেমেন্ট থেকে ভরা হয়। অর্ডারে খরচ হয় — বা মোবাইল রিচার্জে, এখন কেনাকাটা না করতে চাইলে। নগদ হিসেবে তোলা যায় না।'],
  ['Earned on orders that have been delivered. Withdraws to your bank account, or moves into your shopping wallet.', 'डिलीवर हुए ऑर्डर पर अर्जित। आपके बैंक खाते में निकाला जाता है, या आपके शॉपिंग वॉलेट में चला जाता है।', 'ডেলিভারি হওয়া অর্ডারে অর্জিত। আপনার ব্যাংক অ্যাকাউন্টে তোলা যায়, বা আপনার শপিং ওয়ালেটে চলে যায়।'],
  ['Once a recharge is approved it will appear here, along with every order it pays for.', 'रिचार्ज अनुमोदित होने के बाद वह यहाँ दिखेगा, साथ ही हर वह ऑर्डर जिसका वह भुगतान करता है।', 'রিচার্জ অনুমোদিত হলে তা এখানে দেখা যাবে, সঙ্গে প্রতিটি অর্ডার যার পেমেন্ট এ থেকে হয়।'],
  ['Income appears here once an order you or your team placed has been delivered.', 'आप या आपकी टीम का दिया ऑर्डर डिलीवर होने पर आय यहाँ दिखती है।', 'আপনি বা আপনার টিমের দেওয়া অর্ডার ডেলিভারি হলে আয় এখানে দেখা যায়।'],
  // withdraw
  ['Withdraw income', 'आय निकालें', 'আয় তুলুন'],
  ['Withdrawal requested', 'निकासी का अनुरोध किया गया', 'উত্তোলনের অনুরোধ করা হয়েছে'],
  ['See your statement →', 'अपना स्टेटमेंट देखें →', 'আপনার স্টেটমেন্ট দেখুন →'],
  ['How much?', 'कितना?', 'কত?'],
  ['That is more than your income wallet holds.', 'यह आपके इनकम वॉलेट में मौजूद राशि से ज़्यादा है।', 'এটি আপনার ইনকাম ওয়ালেটে থাকা পরিমাণের চেয়ে বেশি।'],
  ['You requested', 'आपने अनुरोध किया', 'আপনি অনুরোধ করেছেন'],
  ['Deduction (', 'कटौती (', 'কর্তন ('],
  ['Reaches your account', 'आपके खाते में पहुँचता है', 'আপনার অ্যাকাউন্টে পৌঁছায়'],
  ['Request withdrawal', 'निकासी का अनुरोध करें', 'উত্তোলনের অনুরোধ করুন'],
  ['Before you can withdraw', 'निकासी से पहले', 'উত্তোলনের আগে'],
  ['Payout details on file', 'पेआउट विवरण दर्ज है', 'পেআউট বিবরণ নথিভুক্ত আছে'],
  ['Add them →', 'उन्हें जोड़ें →', 'সেগুলি যোগ করুন →'],
  ['Repurchase for this period', 'इस अवधि का पुनः-खरीद', 'এই সময়ের পুনঃক্রয়'],
  ['Shop →', 'खरीदें →', 'কিনুন →'],
  ['{amount} will be transferred to your account. The amount has been held from your income wallet already, so it cannot be spent twice while the transfer is processed.', '{amount} आपके खाते में ट्रांसफ़र किए जाएँगे। यह राशि आपके इनकम वॉलेट से पहले ही रोक ली गई है, इसलिए ट्रांसफ़र की प्रक्रिया के दौरान इसे दो बार खर्च नहीं किया जा सकता।', '{amount} আপনার অ্যাকাউন্টে ট্রান্সফার করা হবে। টাকাটি আপনার ইনকাম ওয়ালেট থেকে আগেই আটকে রাখা হয়েছে, তাই ট্রান্সফার প্রক্রিয়ার সময় তা দুবার খরচ করা যাবে না।'],
  ['Withdrawals are checked and paid by our team. The amount is held from your wallet as soon as you request it, so it cannot be spent twice while it is processed.', 'निकासी की जाँच और भुगतान हमारी टीम करती है। अनुरोध करते ही राशि आपके वॉलेट से रोक ली जाती है, इसलिए प्रक्रिया के दौरान इसे दो बार खर्च नहीं किया जा सकता।', 'উত্তোলন আমাদের টিম যাচাই করে ও পেমেন্ট করে। অনুরোধ করামাত্র টাকা আপনার ওয়ালেট থেকে আটকে রাখা হয়, তাই প্রক্রিয়ার সময় তা দুবার খরচ করা যায় না।'],
  ['Payouts go only to an account in your own name.', 'पेआउट केवल आपके अपने नाम के खाते में जाता है।', 'পেআউট শুধু আপনার নিজের নামের অ্যাকাউন্টে যায়।'],
  ['Your shopping wallet cannot be withdrawn — it buys products only.', 'आपका शॉपिंग वॉलेट निकाला नहीं जा सकता — इससे केवल उत्पाद खरीदे जाते हैं।', 'আপনার শপিং ওয়ালেট তোলা যায় না — এটি শুধু পণ্য কেনার জন্য।'],
  ['TDS is deducted where it applies, and shown on your statement.', 'जहाँ लागू हो वहाँ TDS काटा जाता है, और आपके स्टेटमेंट में दिखाया जाता है।', 'যেখানে প্রযোজ্য সেখানে TDS কাটা হয় এবং আপনার স্টেটমেন্টে দেখানো হয়।'],
  // mobile recharge
  ['Mobile recharge', 'मोबाइल रिचार्ज', 'মোবাইল রিচার্জ'],
  ['Recharge requested', 'रिचार्ज का अनुरोध किया गया', 'রিচার্জের অনুরোধ করা হয়েছে'],
  ['Request another →', 'एक और अनुरोध करें →', 'আরেকটি অনুরোধ করুন →'],
  ['Recharge a mobile number', 'मोबाइल नंबर रिचार्ज करें', 'মোবাইল নম্বর রিচার্জ করুন'],
  ['Shopping wallet available:', 'शॉपिंग वॉलेट में उपलब्ध:', 'শপিং ওয়ালেটে উপলব্ধ:'],
  ['Operator', 'ऑपरेटर', 'অপারেটর'],
  ['Checking current plans…', 'मौजूदा प्लान देखे जा रहे हैं…', 'বর্তমান প্ল্যান দেখা হচ্ছে…'],
  ["Couldn't load current plans right now — enter an amount below instead.", 'अभी मौजूदा प्लान लोड नहीं हो सके — इसके बजाय नीचे राशि दर्ज करें।', 'এখন বর্তমান প্ল্যান লোড করা যায়নি — এর বদলে নিচে পরিমাণ দিন।'],
  ['Or enter a custom amount', 'या अपनी राशि दर्ज करें', 'অথবা নিজের পরিমাণ দিন'],
  ['Amount', 'राशि', 'পরিমাণ'],
  ['That is more than your shopping wallet holds.', 'यह आपके शॉपिंग वॉलेट में मौजूद राशि से ज़्यादा है।', 'এটি আপনার শপিং ওয়ালেটে থাকা পরিমাণের চেয়ে বেশি।'],
  ['Recharges are capped at ₹5,000 at a time.', 'एक बार में रिचार्ज ₹5,000 तक सीमित है।', 'একবারে রিচার্জ ₹৫,০০০ পর্যন্ত সীমাবদ্ধ।'],
  ['You already have a recharge in progress — wait for it to complete first.', 'आपका एक रिचार्ज पहले से चल रहा है — पहले उसके पूरा होने की प्रतीक्षा करें।', 'আপনার একটি রিচার্জ ইতিমধ্যে চলছে — আগে সেটি সম্পূর্ণ হওয়ার অপেক্ষা করুন।'],
  ['Submitting…', 'जमा किया जा रहा है…', 'জমা দেওয়া হচ্ছে…'],
  ['Recharge from wallet', 'वॉलेट से रिचार्ज करें', 'ওয়ালেট থেকে রিচার্জ করুন'],
  ['Good to know', 'जानने योग्य', 'জেনে রাখুন'],
  ['Recent recharges', 'हाल के रिचार्ज', 'সাম্প্রতিক রিচার্জ'],
  ['See full wallet statement →', 'पूरा वॉलेट स्टेटमेंट देखें →', 'পুরো ওয়ালেট স্টেটমেন্ট দেখুন →'],
  ['{amount} has been held from your shopping wallet to recharge {number}. It usually completes within a few hours — you’ll get a notification either way.', '{number} को रिचार्ज करने के लिए आपके शॉपिंग वॉलेट से {amount} रोक लिए गए हैं। यह आमतौर पर कुछ घंटों में पूरा हो जाता है — आपको किसी भी स्थिति में सूचना मिलेगी।', '{number} রিচার্জ করতে আপনার শপিং ওয়ালেট থেকে {amount} আটকে রাখা হয়েছে। এটি সাধারণত কয়েক ঘণ্টায় সম্পূর্ণ হয় — যেকোনো ক্ষেত্রে আপনি বিজ্ঞপ্তি পাবেন।'],
  ['The amount is held from your shopping wallet the moment you submit. If we can’t complete the recharge, it goes straight back to your wallet.', 'जमा करते ही राशि आपके शॉपिंग वॉलेट से रोक ली जाती है। यदि हम रिचार्ज पूरा नहीं कर पाए, तो वह सीधे आपके वॉलेट में लौट जाती है।', 'জমা দেওয়ামাত্র টাকা আপনার শপিং ওয়ালেট থেকে আটকে রাখা হয়। রিচার্জ সম্পূর্ণ করতে না পারলে তা সরাসরি আপনার ওয়ালেটে ফিরে যায়।'],
  ['This spends your shopping wallet — the same balance an order would spend.', 'यह आपका शॉपिंग वॉलेट खर्च करता है — वही बैलेंस जो ऑर्डर खर्च करता।', 'এটি আপনার শপিং ওয়ালেট খরচ করে — যে ব্যালেন্স একটি অর্ডার খরচ করত।'],
  ['₹10 minimum, ₹5,000 maximum per recharge, one in progress at a time.', 'प्रति रिचार्ज न्यूनतम ₹10, अधिकतम ₹5,000, एक समय में एक प्रक्रिया में।', 'প্রতি রিচার্জে ন্যূনতম ₹১০, সর্বোচ্চ ₹৫,০০০, একসঙ্গে একটি প্রক্রিয়াধীন।'],
  ['Recharges are fulfilled by our team, usually within a few hours.', 'रिचार्ज हमारी टीम पूरा करती है, आमतौर पर कुछ घंटों में।', 'রিচার্জ আমাদের টিম সম্পূর্ণ করে, সাধারণত কয়েক ঘণ্টার মধ্যে।'],
  // id card
  ['Your ID card', 'आपका आईडी कार्ड', 'আপনার আইডি কার্ড'],
  ['A clear, front-facing photo with your face in the middle. It is cropped to a square.', 'साफ़, सामने से ली गई फ़ोटो जिसमें आपका चेहरा बीच में हो। इसे वर्गाकार काटा जाता है।', 'পরিষ্কার, সামনে থেকে তোলা ছবি যেখানে আপনার মুখ মাঝখানে। এটি বর্গাকারে কাটা হয়।'],
  ['Welcome to Majestic Cart! Add your photo below and your ID card is ready to print.', 'Majestic Cart में आपका स्वागत है! नीचे अपनी फ़ोटो जोड़ें और आपका आईडी कार्ड प्रिंट के लिए तैयार है।', 'Majestic Cart-এ স্বাগতম! নিচে আপনার ছবি যোগ করুন, আপনার আইডি কার্ড প্রিন্টের জন্য প্রস্তুত।'],
  ['Unlocked by what you have achieved.', 'आपकी उपलब्धियों से अनलॉक।', 'আপনার অর্জনে আনলক।'],
];
