import type { Phrase } from './types';

/** Statuses, catalogue blurbs, counts with a number in them, and the small stragglers. */
export const MISC: Phrase[] = [
  // order / recharge / withdrawal statuses (as rendered: first letter capital, rest lower case)
  ['Pending', 'लंबित', 'মুলতুবি'],
  ['Placed', 'दिया गया', 'দেওয়া হয়েছে'],
  ['Packed', 'पैक हो गया', 'প্যাক হয়েছে'],
  ['Shipped', 'शिप हो गया', 'শিপ হয়েছে'],
  ['Approved', 'अनुमोदित', 'অনুমোদিত'],
  ['Delivered', 'डिलीवर हो गया', 'ডেলিভারি হয়েছে'],
  ['Paid', 'भुगतान हो गया', 'পেমেন্ট হয়েছে'],
  ['Rejected', 'अस्वीकृत', 'প্রত্যাখ্যাত'],
  ['Cancelled', 'रद्द', 'বাতিল'],
  ['Returned', 'लौटाया गया', 'ফেরত দেওয়া হয়েছে'],
  ['Rejected (returned to wallet)', 'अस्वीकृत (वॉलेट में लौटाया गया)', 'প্রত্যাখ্যাত (ওয়ালেটে ফেরত)'],
  ['In progress', 'प्रक्रिया में', 'প্রক্রিয়াধীন'],
  ['Completed', 'पूर्ण', 'সম্পূর্ণ'],
  ['Failed', 'विफल', 'ব্যর্থ'],
  // id card
  ['Welcome', 'स्वागत', 'স্বাগতম'],
  ['Target complete', 'लक्ष्य पूरा', 'লক্ষ্য পূরণ'],
  // brand / catalogue
  ['Royal beauty, rewarded', 'शाही सुंदरता, पुरस्कृत', 'রাজকীয় সৌন্দর্য, পুরস্কৃত'],
  ['Skin care, makeup and more — picked from brands already on your shelf.', 'स्किन केयर, मेकअप और बहुत कुछ — उन ब्रांड से चुना गया जो पहले से आपकी शेल्फ़ पर हैं।', 'স্কিন কেয়ার, মেকআপ ও আরও অনেক কিছু — আপনার শেলফে আগে থেকেই থাকা ব্র্যান্ড থেকে বাছাই করা।'],
  ['Colour cosmetics from leading brands.', 'अग्रणी ब्रांड के कलर कॉस्मेटिक्स।', 'শীর্ষস্থানীয় ব্র্যান্ডের কালার প্রসাধনী।'],
  ['Foundations, lipsticks and eye colour from established brands, so you can shop the shades you already know in one place.', 'स्थापित ब्रांड के फ़ाउंडेशन, लिपस्टिक और आई कलर, ताकि आप जिन शेड्स को पहले से जानते हैं उन्हें एक जगह खरीद सकें।', 'প্রতিষ্ঠিত ব্র্যান্ডের ফাউন্ডেশন, লিপস্টিক ও আই কালার, যাতে আপনি যে শেডগুলি আগে থেকে চেনেন তা এক জায়গায় কিনতে পারেন।'],
  ['Serums, cleansers and moisturisers from trusted brands.', 'भरोसेमंद ब्रांड के सीरम, क्लींज़र और मॉइस्चराइज़र।', 'বিশ্বস্ত ব্র্যান্ডের সিরাম, ক্লেনজার ও ময়েশ্চারাইজার।'],
  ['Skin care from established brands — cleansers, moisturisers, serums and sun care for everyday routines.', 'स्थापित ब्रांड का स्किन केयर — रोज़ाना की दिनचर्या के लिए क्लींज़र, मॉइस्चराइज़र, सीरम और सन केयर।', 'প্রতিষ্ঠিত ব্র্যান্ডের স্কিন কেয়ার — প্রতিদিনের রুটিনের জন্য ক্লেনজার, ময়েশ্চারাইজার, সিরাম ও সান কেয়ার।'],
  ['Lotions, butters and washes for everyday skin.', 'रोज़ाना की त्वचा के लिए लोशन, बटर और वॉश।', 'প্রতিদিনের ত্বকের জন্য লোশন, বাটার ও ওয়াশ।'],
  ['Body care for regular use: lotions that absorb rather than sit, butters for dry winter skin, and washes gentle enough for daily showers.', 'नियमित इस्तेमाल के लिए बॉडी केयर: लोशन जो ऊपर बैठने की बजाय सोख लिए जाते हैं, सर्दियों की रूखी त्वचा के लिए बटर, और रोज़ाना नहाने के लिए पर्याप्त कोमल वॉश।', 'নিয়মিত ব্যবহারের জন্য বডি কেয়ার: লোশন যা ওপরে বসে না থেকে শোষিত হয়, শীতের শুষ্ক ত্বকের জন্য বাটার, এবং প্রতিদিনের স্নানের জন্য যথেষ্ট কোমল ওয়াশ।'],
  ['Perfumes and body mists from leading brands.', 'अग्रणी ब्रांड के परफ्यूम और बॉडी मिस्ट।', 'শীর্ষস্থানীয় ব্র্যান্ডের পারফিউম ও বডি মিস্ট।'],
  ['Eau de parfum, deodorants and body mists from established brands, for everyday wear and for evenings.', 'स्थापित ब्रांड के ओ दे परफ़म, डियोडरेंट और बॉडी मिस्ट, रोज़ाना के लिए और शामों के लिए।', 'প্রতিষ্ঠিত ব্র্যান্ডের ও দ্য পারফিউম, ডিওডোরেন্ট ও বডি মিস্ট, প্রতিদিনের জন্য এবং সন্ধ্যার জন্য।'],
  ['Explore the range.', 'रेंज देखें।', 'সংগ্রহ ঘুরে দেখুন।'],
  ['Browse the full selection in this category.', 'इस श्रेणी का पूरा चयन देखें।', 'এই বিভাগের পুরো সংগ্রহ দেখুন।'],
  ['Browse the full selection in this category', 'इस श्रेणी का पूरा चयन देखें', 'এই বিভাগের পুরো সংগ্রহ দেখুন'],
  ['Monday to Saturday, 10am to 7pm IST', 'सोमवार से शनिवार, सुबह 10 बजे से शाम 7 बजे IST', 'সোমবার থেকে শনিবার, সকাল ১০টা থেকে সন্ধ্যা ৭টা IST'],
  ['Grievance Officer', 'शिकायत अधिकारी', 'অভিযোগ কর্মকর্তা'],
  ['by', 'द्वारा', 'দ্বারা'],
  ['Income is earned only on products sold and delivered. We make no guarantee of earnings.', 'आय केवल बेचे और डिलीवर किए गए उत्पादों पर होती है। हम कमाई की कोई गारंटी नहीं देते।', 'আয় শুধু বিক্রি ও ডেলিভারি হওয়া পণ্যে হয়। আমরা আয়ের কোনো নিশ্চয়তা দিই না।'],
  // counts that carry a number
  ['Makeup, skin care, body care and fragrance from leading beauty brands, all in one place.', 'अग्रणी ब्यूटी ब्रांड के मेकअप, स्किन केयर, बॉडी केयर और फ्रेगरेंस, सब एक जगह।', 'শীর্ষস্থানীয় বিউটি ব্র্যান্ডের মেকআপ, স্কিন কেয়ার, বডি কেয়ার ও ফ্র্যাগরেন্স, সব এক জায়গায়।'],
  ["Filled in from the link you followed. You will join {name}'s team.", 'जिस लिंक से आप आए हैं उससे भरा गया। आप {name} की टीम में जुड़ेंगे।', 'আপনার অনুসরণ করা লিঙ্ক থেকে পূরণ করা। আপনি {name}-এর টিমে যোগ দেবেন।'],
  ['India', 'भारत', 'ভারত'],
  ['product', 'उत्पाद', 'পণ্য'],
  ['products', 'उत्पाद', 'পণ্য'],
  ['shown', 'दिखाए गए', 'দেখানো হচ্ছে'],
  ['of', 'में से', 'এর মধ্যে'],
  ['{n} Brands', '{n} ब्रांड', '{n}টি ব্র্যান্ড'],
  ['{n}+ genuine products, and growing.', '{n}+ असली उत्पाद, और बढ़ते हुए।', '{n}+ আসল পণ্য, আর বাড়ছে।'],
  ['{n} products', '{n} उत्पाद', '{n}টি পণ্য'],
  ['{n} product', '{n} उत्पाद', '{n}টি পণ্য'],
  ['{n} in your bag.', 'आपके बैग में {n}।', 'আপনার ব্যাগে {n}টি।'],
  ['Go to slide {n}', 'स्लाइड {n} पर जाएँ', 'স্লাইড {n}-এ যান'],
  ['Shop {name}', '{name} खरीदें', '{name} কিনুন'],
  ['Search "{x}"', 'खोजें "{x}"', 'খুঁজুন "{x}"'],
  ['{n} of {m} shown', '{m} में से {n} दिखाए गए', '{m}টির মধ্যে {n}টি দেখানো হচ্ছে'],
  ['{n} selected', '{n} चुने गए', '{n}টি বেছে নেওয়া হয়েছে'],
  ['{n} BV per unit', 'प्रति यूनिट {n} BV', 'প্রতি ইউনিট {n} BV'],
  ['{n}% off', '{n}% छूट', '{n}% ছাড়'],
  ['{n} off', '{n} की छूट', '{n} ছাড়'],
];
