import type { Phrase } from './types';

/**
 * Public pages, header and footer, shop, bag, checkout and the sign-in forms.
 * [English as it appears on screen, Hindi, Bengali].
 *
 * Brand and technical terms stay in Latin script the way they are used in
 * everyday Indian shopping apps: Majestic Cart, UPI, GST, TDS, OTP, UTR, PIN,
 * BV, MRP, SMS, WhatsApp.
 */
export const UI: Phrase[] = [
  ['About Majestic Cart', 'Majestic Cart के बारे में', 'Majestic Cart সম্পর্কে'],
  ['How the business works', 'यह व्यवसाय कैसे काम करता है', 'ব্যবসাটি কীভাবে কাজ করে'],
  ['The full rules are in our', 'पूरे नियम हमारी', 'পূর্ণ নিয়মগুলি আমাদের'],
  ['terms and conditions', 'नियम और शर्तों', 'শর্তাবলীতে'],
  ['buy-back policy', 'बायबैक नीति', 'বাইব্যাক নীতিতে'],
  ['Shop the range', 'पूरी रेंज देखें', 'পুরো সংগ্রহ দেখুন'],
  ['Become a member', 'सदस्य बनें', 'সদস্য হন'],
  ['Blog', 'ब्लॉग', 'ব্লগ'],
  ['Read more →', 'और पढ़ें →', 'আরও পড়ুন →'],
  ['Breadcrumb', 'ब्रेडक्रंब', 'ব্রেডক্রাম্ব'],
  ['Home', 'होम', 'হোম'],
  ['← All posts', '← सभी पोस्ट', '← সব পোস্ট'],
  ['Shop', 'शॉप', 'শপ'],
  ['Shop all products', 'सभी उत्पाद देखें', 'সব পণ্য দেখুন'],
  ['← Back to all products', '← सभी उत्पादों पर वापस', '← সব পণ্যে ফিরে যান'],
  ['All', 'सभी', 'সব'],
  ['Products are on their way', 'उत्पाद जल्द आ रहे हैं', 'পণ্য শীঘ্রই আসছে'],
  ['Nothing is listed in', 'अभी कुछ भी सूचीबद्ध नहीं है:', 'এখনও কিছু তালিকাভুক্ত নেই:'],
  ['just yet. Have a look at the rest of the range.', 'अभी तक। बाकी रेंज देखें।', 'এখনও। বাকি সংগ্রহটি দেখুন।'],
  ['Contact us', 'संपर्क करें', 'যোগাযোগ করুন'],
  ['Customer care', 'ग्राहक सेवा', 'গ্রাহক সেবা'],
  ['Grievance officer', 'शिकायत अधिकारी', 'অভিযোগ কর্মকর্তা'],
  ['Write to us', 'हमें लिखें', 'আমাদের লিখুন'],
  ['Registered office', 'पंजीकृत कार्यालय', 'নিবন্ধিত অফিস'],
  ['Udyam Reg. No.', 'उद्यम पंजीकरण सं.', 'উদ্যম নিবন্ধন নং'],
  ['· GSTIN', '· GSTIN', '· GSTIN'],
  ['Frequently asked questions', 'अक्सर पूछे जाने वाले प्रश्न', 'সাধারণ প্রশ্নাবলী'],
  ['Ordering, the wallet, delivery, returns and membership.', 'ऑर्डर, वॉलेट, डिलीवरी, वापसी और सदस्यता।', 'অর্ডার, ওয়ালেট, ডেলিভারি, ফেরত ও সদস্যপদ।'],
  ['Still stuck?', 'अब भी दिक्कत है?', 'এখনও সমস্যা হচ্ছে?'],
  ['Customer care is open', 'ग्राहक सेवा खुली है:', 'গ্রাহক সেবা খোলা থাকে:'],
  ['Contact us →', 'संपर्क करें →', 'যোগাযোগ করুন →'],
  ['Reset your password', 'अपना पासवर्ड रीसेट करें', 'আপনার পাসওয়ার্ড রিসেট করুন'],
  ['Back to log in', 'लॉग इन पर वापस', 'লগ ইনে ফিরে যান'],
  ['Registered email address', 'पंजीकृत ईमेल पता', 'নিবন্ধিত ইমেইল ঠিকানা'],
  ['Send code', 'कोड भेजें', 'কোড পাঠান'],
  ['If that email is registered, a code arrives within a minute. It expires in 10 minutes. Never share it with anyone — our staff will never ask you for it.', 'यदि वह ईमेल पंजीकृत है, तो एक मिनट के भीतर कोड आ जाएगा। यह 10 मिनट में समाप्त हो जाता है। इसे किसी के साथ साझा न करें — हमारा स्टाफ कभी इसे नहीं माँगेगा।', 'ওই ইমেইল নিবন্ধিত থাকলে এক মিনিটের মধ্যে কোড আসবে। এটি ১০ মিনিটে মেয়াদোত্তীর্ণ হয়। কারও সঙ্গে শেয়ার করবেন না — আমাদের কর্মীরা কখনও এটি চাইবে না।'],
  ['Changed your email?', 'ईमेल बदल गया है?', 'ইমেইল বদলেছেন?'],
  ['Contact customer care', 'ग्राहक सेवा से संपर्क करें', 'গ্রাহক সেবার সঙ্গে যোগাযোগ করুন'],
  ['How it works', 'यह कैसे काम करता है', 'এটি কীভাবে কাজ করে'],
  ['The rules we hold ourselves to', 'वे नियम जिनका हम स्वयं पालन करते हैं', 'যে নিয়মগুলি আমরা নিজেরা মেনে চলি'],
  ['Who can join', 'कौन जुड़ सकता है', 'কে যোগ দিতে পারেন'],
  ['Create your account', 'अपना खाता बनाएँ', 'আপনার অ্যাকাউন্ট তৈরি করুন'],
  ['Read the FAQ', 'FAQ पढ़ें', 'FAQ পড়ুন'],
  ['The compensation plan in full — every rate, rank and qualification rule — is published inside your account once you have signed up, together with the published income distribution for all members.', 'पूरी कम्पन्सेशन प्लान — हर दर, रैंक और पात्रता नियम — साइन अप करने के बाद आपके खाते के भीतर प्रकाशित है, साथ ही सभी सदस्यों के लिए प्रकाशित आय वितरण भी।', 'সম্পূর্ণ কমপেনসেশন প্ল্যান — প্রতিটি হার, র‍্যাঙ্ক ও যোগ্যতার নিয়ম — সাইন আপ করার পর আপনার অ্যাকাউন্টের ভেতরে প্রকাশিত আছে, সঙ্গে সব সদস্যের প্রকাশিত আয় বণ্টনও।'],
  ['Skip to content', 'सीधे सामग्री पर जाएँ', 'সরাসরি বিষয়বস্তুতে যান'],
  ['Welcome back', 'वापसी पर स्वागत है', 'ফিরে আসায় স্বাগতম'],
  ['New here?', 'यहाँ नए हैं?', 'এখানে নতুন?'],
  ['Create a free account', 'मुफ़्त खाता बनाएँ', 'বিনামূল্যে অ্যাকাউন্ট তৈরি করুন'],
  ['Password reset. Log in with your new password.', 'पासवर्ड रीसेट हो गया। अपने नए पासवर्ड से लॉग इन करें।', 'পাসওয়ার্ড রিসেট হয়েছে। নতুন পাসওয়ার্ড দিয়ে লগ ইন করুন।'],
  ['Mobile number or member ID', 'मोबाइल नंबर या सदस्य आईडी', 'মোবাইল নম্বর বা সদস্য আইডি'],
  ['Password', 'पासवर्ड', 'পাসওয়ার্ড'],
  ['Forgot password?', 'पासवर्ड भूल गए?', 'পাসওয়ার্ড ভুলে গেছেন?'],
  ['Log in', 'लॉग इन', 'লগ ইন'],
  ['Trouble logging in? Call customer care rather than sharing your password with anyone. We will never ask you for your password or an OTP.', 'लॉग इन में दिक्कत है? अपना पासवर्ड किसी से साझा करने के बजाय ग्राहक सेवा को कॉल करें। हम आपसे कभी आपका पासवर्ड या OTP नहीं माँगेंगे।', 'লগ ইনে সমস্যা? কারও সঙ্গে পাসওয়ার্ড শেয়ার না করে গ্রাহক সেবায় কল করুন। আমরা কখনও আপনার পাসওয়ার্ড বা OTP চাইব না।'],
  ["'s storefront", ' का स्टोरफ्रंट', ' এর স্টোরফ্রন্ট'],
  ['You are offline', 'आप ऑफ़लाइन हैं', 'আপনি অফলাইনে আছেন'],
  ['This page needs a connection. Your wallet and orders are always shown live, never from a cached copy, so they are unavailable until you reconnect.', 'इस पेज के लिए कनेक्शन चाहिए। आपका वॉलेट और ऑर्डर हमेशा लाइव दिखाए जाते हैं, कैश की गई कॉपी से कभी नहीं, इसलिए दोबारा कनेक्ट होने तक वे उपलब्ध नहीं हैं।', 'এই পেজের জন্য সংযোগ দরকার। আপনার ওয়ালেট ও অর্ডার সবসময় লাইভ দেখানো হয়, ক্যাশ কপি থেকে কখনও নয়, তাই আবার সংযুক্ত না হওয়া পর্যন্ত সেগুলি পাওয়া যাবে না।'],
  ['Go home', 'होम पर जाएँ', 'হোমে যান'],
  ['Browse →', 'देखें →', 'ব্রাউজ করুন →'],
  ['View all →', 'सभी देखें →', 'সব দেখুন →'],
  ['Read our story →', 'हमारी कहानी पढ़ें →', 'আমাদের গল্প পড়ুন →'],
  ['Open →', 'खोलें →', 'খুলুন →'],
  ['Please be alert to fraudulent calls and messages.', 'कृपया धोखाधड़ी वाले कॉल और संदेशों से सावधान रहें।', 'প্রতারণামূলক কল ও বার্তা থেকে সতর্ক থাকুন।'],
  ['does not call or message you about gifts, offers, discounts, prizes or freebies, and never asks for payment through a link or for your password or OTP.', 'आपको उपहार, ऑफ़र, छूट, इनाम या मुफ़्त चीज़ों के बारे में कॉल या संदेश नहीं करता, और कभी किसी लिंक के ज़रिए भुगतान या आपका पासवर्ड या OTP नहीं माँगता।', 'উপহার, অফার, ছাড়, পুরস্কার বা বিনামূল্যের জিনিস নিয়ে আপনাকে কল বা বার্তা পাঠায় না, এবং কখনও লিঙ্কের মাধ্যমে পেমেন্ট বা আপনার পাসওয়ার্ড বা OTP চায় না।'],
  ['Price includes GST', 'कीमत में GST शामिल है', 'দামে GST অন্তর্ভুক্ত'],
  ['per unit for members', 'सदस्यों के लिए प्रति यूनिट', 'সদস্যদের জন্য প্রতি ইউনিট'],
  ['About this product', 'इस उत्पाद के बारे में', 'এই পণ্য সম্পর্কে'],
  ['How to use', 'कैसे इस्तेमाल करें', 'কীভাবে ব্যবহার করবেন'],
  ['Ingredients', 'सामग्री', 'উপকরণ'],
  ['Country of origin', 'उत्पत्ति का देश', 'উৎপত্তির দেশ'],
  ['% (included)', '% (शामिल)', '% (অন্তর্ভুক্ত)'],
  ['Orders are paid from your shopping wallet.', 'ऑर्डर का भुगतान आपके शॉपिंग वॉलेट से होता है।', 'অর্ডারের পেমেন্ট আপনার শপিং ওয়ালেট থেকে হয়।'],
  ['How that works', 'यह कैसे काम करता है', 'এটি কীভাবে কাজ করে'],
  ['More in', 'और देखें:', 'আরও দেখুন:'],
  ['Enter your reset code', 'अपना रीसेट कोड दर्ज करें', 'আপনার রিসেট কোড দিন'],
  ['The code was emailed to you, if that address is registered.', 'यदि वह पता पंजीकृत है, तो कोड आपको ईमेल किया गया है।', 'ঠিকানাটি নিবন্ধিত থাকলে কোডটি আপনাকে ইমেইল করা হয়েছে।'],
  ['Email address', 'ईमेल पता', 'ইমেইল ঠিকানা'],
  ['6-digit code', '6 अंकों का कोड', '৬ সংখ্যার কোড'],
  ['Expires 10 minutes after it was sent.', 'भेजे जाने के 10 मिनट बाद समाप्त हो जाता है।', 'পাঠানোর ১০ মিনিট পর মেয়াদ শেষ হয়।'],
  ['New password', 'नया पासवर्ड', 'নতুন পাসওয়ার্ড'],
  ['At least 8 characters. Avoid your name or phone number.', 'कम से कम 8 अक्षर। अपना नाम या फ़ोन नंबर इस्तेमाल न करें।', 'কমপক্ষে ৮ অক্ষর। আপনার নাম বা ফোন নম্বর ব্যবহার করবেন না।'],
  ['Set new password', 'नया पासवर्ड सेट करें', 'নতুন পাসওয়ার্ড সেট করুন'],
  ["Didn't get a code?", 'कोड नहीं मिला?', 'কোড পাননি?'],
  ['Send it again', 'दोबारा भेजें', 'আবার পাঠান'],
  ['Search', 'खोजें', 'সার্চ'],
  ['Type a product, brand or category name to search.', 'खोजने के लिए कोई उत्पाद, ब्रांड या श्रेणी का नाम लिखें।', 'খুঁজতে কোনো পণ্য, ব্র্যান্ড বা বিভাগের নাম লিখুন।'],
  ['Nothing matched “', 'कुछ भी नहीं मिला “', 'কিছু মেলেনি “'],
  ['”', '”', '”'],
  ['Try a shorter or more general search term.', 'कोई छोटा या सामान्य शब्द आज़माएँ।', 'আরও ছোট বা সাধারণ শব্দ দিয়ে চেষ্টা করুন।'],
  ['All products', 'सभी उत्पाद', 'সব পণ্য'],
  ['Shop by category', 'श्रेणी के अनुसार खरीदें', 'বিভাগ অনুযায়ী কিনুন'],
  ['Join Majestic Cart', 'Majestic Cart से जुड़ें', 'Majestic Cart-এ যোগ দিন'],
  ['Already a member?', 'पहले से सदस्य हैं?', 'ইতিমধ্যে সদস্য?'],
  ['Full name', 'पूरा नाम', 'পুরো নাম'],
  ['Mobile number', 'मोबाइल नंबर', 'মোবাইল নম্বর'],
  ['We send a one-time code to verify it.', 'सत्यापन के लिए हम एक वन-टाइम कोड भेजते हैं।', 'যাচাইয়ের জন্য আমরা একটি ওয়ান-টাইম কোড পাঠাই।'],
  ['Email', 'ईमेल', 'ইমেইল'],
  ['For order updates and account recovery.', 'ऑर्डर अपडेट और खाता रिकवरी के लिए।', 'অর্ডার আপডেট ও অ্যাকাউন্ট পুনরুদ্ধারের জন্য।'],
  ['Referral ID', 'रेफ़रल आईडी', 'রেফারেল আইডি'],
  ['Ask whoever invited you for their Referral ID, or open the invite link they sent you.', 'जिसने आपको आमंत्रित किया उससे उनकी रेफ़रल आईडी माँगें, या उनका भेजा आमंत्रण लिंक खोलें।', 'যিনি আপনাকে আমন্ত্রণ জানিয়েছেন তাঁর রেফারেল আইডি চেয়ে নিন, বা তাঁর পাঠানো আমন্ত্রণ লিঙ্ক খুলুন।'],
  ['Create free account', 'मुफ़्त खाता बनाएँ', 'বিনামূল্যে অ্যাকাউন্ট তৈরি করুন'],
  ['By joining you accept our', 'जुड़कर आप हमारी', 'যোগ দিয়ে আপনি আমাদের'],
  ['terms', 'शर्तें', 'শর্তাবলী'],
  ['and', 'और', 'এবং'],
  ['privacy policy', 'गोपनीयता नीति', 'গোপনীয়তা নীতি'],
  ['Skin Care', 'स्किन केयर', 'স্কিন কেয়ার'],
  ['Makeup', 'मेकअप', 'মেকআপ'],
  ['Hair Care', 'हेयर केयर', 'হেয়ার কেয়ার'],
  ['Personal Care', 'पर्सनल केयर', 'পার্সোনাল কেয়ার'],
  ['Fragrance', 'फ्रेगरेंस', 'ফ্র্যাগরেন্স'],
  ['Bath & Body', 'बाथ और बॉडी', 'বাথ ও বডি'],
  ['Skin care', 'स्किन केयर', 'স্কিন কেয়ার'],
  ['Body care', 'बॉडी केयर', 'বডি কেয়ার'],
  ['Lip Care', 'लिप केयर', 'লিপ কেয়ার'],
  ['Eye Care', 'आई केयर', 'আই কেয়ার'],
  ['Moisturizers', 'मॉइस्चराइज़र', 'ময়েশ্চারাইজার'],
  ['Masks', 'मास्क', 'মাস্ক'],
  ['Facial Kit', 'फेशियल किट', 'ফেসিয়াল কিট'],
  ['Aromatherapy', 'अरोमाथेरेपी', 'অ্যারোমাথেরাপি'],
  ['Specialised Skincare', 'विशेष स्किनकेयर', 'বিশেষ স্কিনকেয়ার'],
  ['Toners & Face Mists', 'टोनर और फेस मिस्ट', 'টোনার ও ফেস মিস্ট'],
  ['Skin Care Gifts & Value Sets', 'स्किन केयर गिफ्ट और वैल्यू सेट', 'স্কিন কেয়ার গিফট ও ভ্যালু সেট'],
  ['Eye Makeup', 'आई मेकअप', 'আই মেকআপ'],
  ['Face Makeup', 'फेस मेकअप', 'ফেস মেকআপ'],
  ['Lip Makeup', 'लिप मेकअप', 'লিপ মেকআপ'],
  ['Nails', 'नेल्स', 'নখ'],
  ['Brushes & Tools', 'ब्रश और टूल्स', 'ব্রাশ ও টুলস'],
  ['Makeup Gifts & Value Sets', 'मेकअप गिफ्ट और वैल्यू सेट', 'মেকআপ গিফট ও ভ্যালু সেট'],
  ['Hair Accessories', 'हेयर एक्सेसरीज़', 'হেয়ার অ্যাক্সেসরিজ'],
  ['Hair Styling', 'हेयर स्टाइलिंग', 'হেয়ার স্টাইলিং'],
  ['Shampoo & Conditioners', 'शैम्पू और कंडीशनर', 'শ্যাম্পু ও কন্ডিশনার'],
  ['Hair Nourishment', 'हेयर पोषण', 'হেয়ার পুষ্টি'],
  ['Hair Care & Styling Tools', 'हेयर केयर और स्टाइलिंग टूल्स', 'হেয়ার কেয়ার ও স্টাইলিং টুলস'],
  ['Hair Care Gifts and Value Sets', 'हेयर केयर गिफ्ट और वैल्यू सेट', 'হেয়ার কেয়ার গিফট ও ভ্যালু সেট'],
  ['Diet & Nutrition', 'डाइट और न्यूट्रिशन', 'ডায়েট ও নিউট্রিশন'],
  ['Shaving & Hair Removal', 'शेविंग और हेयर रिमूवल', 'শেভিং ও হেয়ার রিমুভাল'],
  ['Feminine Hygiene', 'फेमिनिन हाइजीन', 'ফেমিনিন হাইজিন'],
  ['Oral Care', 'ओरल केयर', 'ওরাল কেয়ার'],
  ['Gifts and Value Sets - Mom & Baby', 'गिफ्ट और वैल्यू सेट - माँ और बच्चा', 'গিফট ও ভ্যালু সেট - মা ও শিশু'],
  ['Fragrance for Women', 'महिलाओं के लिए फ्रेगरेंस', 'মহিলাদের জন্য ফ্র্যাগরেন্স'],
  ['Perfume for Men', 'पुरुषों के लिए परफ्यूम', 'পুরুষদের জন্য পারফিউম'],
  ['Gifts and Value Sets - Fragrance', 'गिफ्ट और वैल्यू सेट - फ्रेगरेंस', 'গিফট ও ভ্যালু সেট - ফ্র্যাগরেন্স'],
  ['Body Care', 'बॉडी केयर', 'বডি কেয়ার'],
  ['Baby Care', 'बेबी केयर', 'বেবি কেয়ার'],
  ['Bath and Body Care Gifts and Value Sets', 'बाथ और बॉडी केयर गिफ्ट और वैल्यू सेट', 'বাথ ও বডি কেয়ার গিফট ও ভ্যালু সেট'],
  ['Go to bag', 'बैग में जाएँ', 'ব্যাগে যান'],
  ['Decrease quantity', 'मात्रा घटाएँ', 'পরিমাণ কমান'],
  ['Increase quantity', 'मात्रा बढ़ाएँ', 'পরিমাণ বাড়ান'],
  ['Added to your bag.', 'आपके बैग में जोड़ दिया गया।', 'আপনার ব্যাগে যোগ করা হয়েছে।'],
  ['View bag →', 'बैग देखें →', 'ব্যাগ দেখুন →'],
  ['Out of stock. This product will be back — check the shop for what is available now.', 'स्टॉक में नहीं है। यह उत्पाद फिर आएगा — अभी क्या उपलब्ध है यह शॉप में देखें।', 'স্টকে নেই। এই পণ্য আবার আসবে — এখন কী পাওয়া যাচ্ছে তা শপে দেখুন।'],
  ['Announcement', 'घोषणा', 'ঘোষণা'],
  ['Out of stock', 'स्टॉक में नहीं', 'স্টকে নেই'],
  ['Your bag is empty', 'आपका बैग खाली है', 'আপনার ব্যাগ খালি'],
  ['Your bag', 'आपका बैग', 'আপনার ব্যাগ'],
  ['Summary', 'सारांश', 'সারসংক্ষেপ'],
  ['Subtotal', 'उप-योग', 'উপমোট'],
  ['You save', 'आपकी बचत', 'আপনার সাশ্রয়'],
  ['Business volume', 'बिज़नेस वॉल्यूम', 'বিজনেস ভলিউম'],
  ['Checkout', 'चेकआउट', 'চেকআউট'],
  ['Paid from your shopping wallet', 'आपके शॉपिंग वॉलेट से भुगतान', 'আপনার শপিং ওয়ালেট থেকে পেমেন্ট'],
  ['Continue shopping', 'खरीदारी जारी रखें', 'কেনাকাটা চালিয়ে যান'],
  ['Nothing to check out', 'चेकआउट के लिए कुछ नहीं है', 'চেকআউট করার মতো কিছু নেই'],
  ['Your bag is empty.', 'आपका बैग खाली है।', 'আপনার ব্যাগ খালি।'],
  ['Delivery address', 'डिलीवरी का पता', 'ডেলিভারির ঠিকানা'],
  ['10 digits, for delivery updates', '10 अंक, डिलीवरी अपडेट के लिए', '১০ সংখ্যা, ডেলিভারি আপডেটের জন্য'],
  ['Address', 'पता', 'ঠিকানা'],
  ['House or flat number, street, area, landmark', 'मकान या फ्लैट नंबर, गली, इलाका, लैंडमार्क', 'বাড়ি বা ফ্ল্যাট নম্বর, রাস্তা, এলাকা, ল্যান্ডমার্ক'],
  ['City', 'शहर', 'শহর'],
  ['State', 'राज्य', 'রাজ্য'],
  ['Choose a state', 'राज्य चुनें', 'রাজ্য বেছে নিন'],
  ['PIN code', 'पिन कोड', 'পিন কোড'],
  ['Order summary', 'ऑर्डर सारांश', 'অর্ডারের সারসংক্ষেপ'],
  ['Coupon code', 'कूपन कोड', 'কুপন কোড'],
  ['Apply', 'लागू करें', 'প্রয়োগ করুন'],
  ['Item total at MRP', 'MRP पर आइटम का कुल', 'MRP-তে আইটেমের মোট'],
  ['Discount', 'छूट', 'ছাড়'],
  ['Total', 'कुल', 'মোট'],
  ['of which', 'जिसमें से', 'যার মধ্যে'],
  ['Prices include GST. Place of supply:', 'कीमतों में GST शामिल है। आपूर्ति का स्थान:', 'দামে GST অন্তর্ভুক্ত। সরবরাহের স্থান:'],
  ['Choose a state to confirm the total.', 'कुल राशि पक्की करने के लिए राज्य चुनें।', 'মোট নিশ্চিত করতে রাজ্য বেছে নিন।'],
  ['Payment', 'भुगतान', 'পেমেন্ট'],
  ['Shopping wallet', 'शॉपिंग वॉलेट', 'শপিং ওয়ালেট'],
  ['Add at least', 'कम से कम जोड़ें', 'কমপক্ষে যোগ করুন'],
  ['to your shopping wallet. Your bag will still be here when you come back.', 'अपने शॉपिंग वॉलेट में। आपके लौटने पर आपका बैग यहीं रहेगा।', 'আপনার শপিং ওয়ালেটে। আপনি ফিরে এলে আপনার ব্যাগ এখানেই থাকবে।'],
  ['Add money to wallet', 'वॉलेट में पैसे जोड़ें', 'ওয়ালেটে টাকা যোগ করুন'],
  ['Placing your order…', 'आपका ऑर्डर दिया जा रहा है…', 'আপনার অর্ডার দেওয়া হচ্ছে…'],
  ['Fill in the delivery address to continue.', 'आगे बढ़ने के लिए डिलीवरी का पता भरें।', 'এগোতে ডেলিভারির ঠিকানা পূরণ করুন।'],
  ['Wallet', 'वॉलेट', 'ওয়ালেট'],
  ['Bag', 'बैग', 'ব্যাগ'],
  ['Main', 'मुख्य', 'প্রধান'],
  ['Search products, brands…', 'उत्पाद, ब्रांड खोजें…', 'পণ্য, ব্র্যান্ড খুঁজুন…'],
  ['Company', 'कंपनी', 'কোম্পানি'],
  ['Acknowledged within 48 hours', '48 घंटे के भीतर स्वीकार किया जाता है', '৪৮ ঘণ্টার মধ্যে স্বীকৃতি দেওয়া হয়'],
  ['Registering is free. There is no registration fee; earning requires a minimum first order, as set out in the compensation plan. Income is earned only on products that are sold and delivered, and depends entirely on the sales you and your team make. We make no guarantee of earnings.', 'पंजीकरण मुफ़्त है। कोई पंजीकरण शुल्क नहीं है; कमाई के लिए कम्पन्सेशन प्लान में बताए अनुसार न्यूनतम पहला ऑर्डर ज़रूरी है। आय केवल बेचे और डिलीवर किए गए उत्पादों पर होती है, और पूरी तरह आपकी और आपकी टीम की बिक्री पर निर्भर करती है। हम कमाई की कोई गारंटी नहीं देते।', 'নিবন্ধন বিনামূল্যে। কোনো নিবন্ধন ফি নেই; আয় করতে কমপেনসেশন প্ল্যানে উল্লিখিত ন্যূনতম প্রথম অর্ডার দরকার। আয় শুধু বিক্রি ও ডেলিভারি হওয়া পণ্যে হয় এবং সম্পূর্ণ আপনার ও আপনার টিমের বিক্রির ওপর নির্ভর করে। আমরা আয়ের কোনো নিশ্চয়তা দিই না।'],
  ['. All rights reserved.', '. सर्वाधिकार सुरक्षित।', '. সর্বস্বত্ব সংরক্ষিত।'],
  ['Developed with', 'विकसित किया गया', 'তৈরি করা হয়েছে'],
  ['Cre8nex — Digital Marketing & Software', 'Cre8nex — डिजिटल मार्केटिंग और सॉफ्टवेयर', 'Cre8nex — ডিজিটাল মার্কেটিং ও সফটওয়্যার'],
  ['Thank you. Your reference is', 'धन्यवाद। आपका संदर्भ नंबर है', 'ধন্যবাদ। আপনার রেফারেন্স হল'],
  ['. We acknowledge every message within 48 hours, on the phone number or email you gave.', '. हम हर संदेश को 48 घंटे के भीतर, आपके दिए फ़ोन नंबर या ईमेल पर स्वीकार करते हैं।', '. আমরা প্রতিটি বার্তা ৪৮ ঘণ্টার মধ্যে, আপনার দেওয়া ফোন নম্বর বা ইমেইলে স্বীকার করি।'],
  ['Your name', 'आपका नाम', 'আপনার নাম'],
  ['Phone or email', 'फ़ोन या ईमेल', 'ফোন বা ইমেইল'],
  ['Subject', 'विषय', 'বিষয়'],
  ['Message', 'संदेश', 'বার্তা'],
  ['Sending…', 'भेजा जा रहा है…', 'পাঠানো হচ্ছে…'],
  ['Send message', 'संदेश भेजें', 'বার্তা পাঠান'],
  ['Minimum price in rupees', 'न्यूनतम कीमत रुपयों में', 'রুপিতে সর্বনিম্ন দাম'],
  ['Maximum price in rupees', 'अधिकतम कीमत रुपयों में', 'রুপিতে সর্বোচ্চ দাম'],
  ['Minimum business volume', 'न्यूनतम बिज़नेस वॉल्यूम', 'সর্বনিম্ন বিজনেস ভলিউম'],
  ['Maximum business volume', 'अधिकतम बिज़नेस वॉल्यूम', 'সর্বোচ্চ বিজনেস ভলিউম'],
  ['Sort by', 'क्रमबद्ध करें', 'সাজান'],
  ['Sort By', 'क्रमबद्ध करें', 'সাজান'],
  ['Showing', 'दिखा रहे हैं', 'দেখানো হচ্ছে'],
  ['Products', 'उत्पाद', 'পণ্য'],
  ['Close', 'बंद करें', 'বন্ধ করুন'],
  ['Done', 'हो गया', 'হয়েছে'],
  ['Sort', 'क्रम', 'ক্রম'],
  ['Featured', 'विशेष', 'বিশেষ'],
  ['Price: low to high', 'कीमत: कम से ज़्यादा', 'দাম: কম থেকে বেশি'],
  ['Price: high to low', 'कीमत: ज़्यादा से कम', 'দাম: বেশি থেকে কম'],
  ['Highest BV', 'सबसे ज़्यादा BV', 'সর্বোচ্চ BV'],
  ['Biggest discount', 'सबसे बड़ी छूट', 'সবচেয়ে বড় ছাড়'],
  ['No products match these filters', 'इन फ़िल्टर से कोई उत्पाद मेल नहीं खाता', 'এই ফিল্টারের সঙ্গে কোনো পণ্য মেলে না'],
  ['Clear all filters', 'सभी फ़िल्टर हटाएँ', 'সব ফিল্টার মুছুন'],
  ['Previous slide', 'पिछली स्लाइड', 'আগের স্লাইড'],
  ['Next slide', 'अगली स्लाइड', 'পরের স্লাইড'],
  ['Install the Majestic Cart app', 'Majestic Cart ऐप इंस्टॉल करें', 'Majestic Cart অ্যাপ ইনস্টল করুন'],
  ['Get the app', 'ऐप पाएँ', 'অ্যাপ নিন'],
  ['Install', 'इंस्टॉल करें', 'ইনস্টল করুন'],
  ['Link copied', 'लिंक कॉपी हो गया', 'লিঙ্ক কপি হয়েছে'],
  ['Copy link', 'लिंक कॉपी करें', 'লিঙ্ক কপি করুন'],
  ['Not now', 'अभी नहीं', 'এখন নয়'],
  ['We will not ask again for a week.', 'हम एक हफ़्ते तक दोबारा नहीं पूछेंगे।', 'আমরা এক সপ্তাহ আর জিজ্ঞাসা করব না।'],
  ['Try again', 'फिर कोशिश करें', 'আবার চেষ্টা করুন'],
  ['Quick navigation', 'त्वरित नेविगेशन', 'দ্রুত নেভিগেশন'],
  ['Departments', 'विभाग', 'বিভাগসমূহ'],
  ['Close menu', 'मेन्यू बंद करें', 'মেনু বন্ধ করুন'],
  ['Open menu', 'मेन्यू खोलें', 'মেনু খুলুন'],
  ['Search products and brands', 'उत्पाद और ब्रांड खोजें', 'পণ্য ও ব্র্যান্ড খুঁজুন'],
  ['Stop listening', 'सुनना बंद करें', 'শোনা বন্ধ করুন'],
  ['Search by voice', 'आवाज़ से खोजें', 'ভয়েসে খুঁজুন'],
  ['Account', 'खाता', 'অ্যাকাউন্ট'],
  ['Hot deal', 'हॉट डील', 'হট ডিল'],
  ['% off', '% छूट', '% ছাড়'],
  ['per unit', 'प्रति यूनिट', 'প্রতি ইউনিট'],
  ['Nothing here just yet. New pieces are added every week.', 'अभी यहाँ कुछ नहीं है। हर हफ़्ते नए उत्पाद जोड़े जाते हैं।', 'এখনও এখানে কিছু নেই। প্রতি সপ্তাহে নতুন পণ্য যোগ হয়।'],
  ['Brands we carry', 'हमारे ब्रांड', 'আমাদের ব্র্যান্ড'],
  ['Shop Now', 'अभी खरीदें', 'এখনই কিনুন'],
  ['New this season', 'इस सीज़न में नया', 'এই মরসুমে নতুন'],
  ['Explore Majestic Cart', 'Majestic Cart देखें', 'Majestic Cart ঘুরে দেখুন'],
  ['A quick map of the site — everything below has its own page with more detail.', 'साइट का एक त्वरित नक्शा — नीचे हर चीज़ का अपना पेज है जिसमें और जानकारी है।', 'সাইটের একটি দ্রুত মানচিত্র — নিচের প্রতিটির নিজস্ব পেজ আছে যেখানে আরও বিস্তারিত রয়েছে।'],
  ['Secure wallet payments', 'सुरक्षित वॉलेट भुगतान', 'নিরাপদ ওয়ালেট পেমেন্ট'],
  ['Authentic brands only', 'केवल असली ब्रांड', 'শুধু আসল ব্র্যান্ড'],
  ['Delivered pan-India', 'पूरे भारत में डिलीवरी', 'সারা ভারতে ডেলিভারি'],
  ['Brands you already know', 'वे ब्रांड जिन्हें आप पहले से जानते हैं', 'যে ব্র্যান্ডগুলি আপনি আগে থেকেই চেনেন'],
  ['Everything we sell is made by other established beauty brands. We do not manufacture products or sell under our own brand name.', 'हम जो कुछ बेचते हैं वह अन्य स्थापित ब्यूटी ब्रांड द्वारा बनाया गया है। हम उत्पाद नहीं बनाते और न ही अपने ब्रांड नाम से बेचते हैं।', 'আমরা যা বিক্রি করি তা অন্যান্য প্রতিষ্ঠিত বিউটি ব্র্যান্ডের তৈরি। আমরা পণ্য তৈরি করি না বা নিজেদের ব্র্যান্ড নামে বিক্রি করি না।'],
  ['Wallet-based ordering', 'वॉलेट आधारित ऑर्डर', 'ওয়ালেট-ভিত্তিক অর্ডার'],
  ['Add funds to your wallet by UPI, and every order draws from that balance — or recharge your own mobile number if you change your mind about shopping. No card details ever touch the site.', 'UPI से अपने वॉलेट में पैसे जोड़ें, और हर ऑर्डर उसी बैलेंस से होता है — या खरीदारी का मन बदलने पर अपना मोबाइल नंबर रिचार्ज करें। कार्ड की कोई जानकारी साइट को कभी नहीं छूती।', 'UPI-তে আপনার ওয়ালেটে টাকা যোগ করুন, প্রতিটি অর্ডার সেই ব্যালেন্স থেকে হয় — বা কেনাকাটার মত বদলালে নিজের মোবাইল নম্বর রিচার্জ করুন। কার্ডের কোনো তথ্য কখনও সাইটে আসে না।'],
  ['Delivered across India', 'पूरे भारत में डिलीवरी', 'সারা ভারতে ডেলিভারি'],
  ['Tracking on every order, and a returns window set out in full in the refund policy.', 'हर ऑर्डर पर ट्रैकिंग, और रिफंड नीति में पूरी तरह बताई गई वापसी की अवधि।', 'প্রতিটি অর্ডারে ট্র্যাকিং, এবং রিফান্ড নীতিতে পূর্ণভাবে উল্লিখিত ফেরতের সময়সীমা।'],
  ['Pan-India Delivery', 'पूरे भारत में डिलीवरी', 'সারা ভারতে ডেলিভারি'],
  ['Tracking on every order, wherever you are.', 'हर ऑर्डर पर ट्रैकिंग, आप जहाँ भी हों।', 'আপনি যেখানেই থাকুন, প্রতিটি অর্ডারে ট্র্যাকিং।'],
  ['Authentic Products', 'असली उत्पाद', 'আসল পণ্য'],
  ['Sourced directly from brands and authorised distributors.', 'सीधे ब्रांड और अधिकृत वितरकों से प्राप्त।', 'সরাসরি ব্র্যান্ড ও অনুমোদিত বিতরকদের কাছ থেকে সংগৃহীত।'],
  ['Easy Returns', 'आसान वापसी', 'সহজ ফেরত'],
  ['A return window set out in full in the refund policy.', 'रिफंड नीति में पूरी तरह बताई गई वापसी की अवधि।', 'রিফান্ড নীতিতে পূর্ণভাবে উল্লিখিত ফেরতের সময়সীমা।'],
  ['Makeup, skin care, body care and fragrance — the full catalogue, or browse by category.', 'मेकअप, स्किन केयर, बॉडी केयर और फ्रेगरेंस — पूरा कैटलॉग, या श्रेणी के अनुसार देखें।', 'মেকআপ, স্কিন কেয়ার, বডি কেয়ার ও ফ্র্যাগরেন্স — পুরো ক্যাটালগ, অথবা বিভাগ অনুযায়ী দেখুন।'],
  ['AI shade finder', 'AI शेड फ़ाइंडर', 'AI শেড ফাইন্ডার'],
  ['Upload a selfie and get shade suggestions from the current makeup range.', 'सेल्फ़ी अपलोड करें और मौजूदा मेकअप रेंज से शेड सुझाव पाएँ।', 'সেলফি আপলোড করুন এবং বর্তমান মেকআপ সংগ্রহ থেকে শেড পরামর্শ পান।'],
  ['Wallet & recharge', 'वॉलेट और रिचार्ज', 'ওয়ালেট ও রিচার্জ'],
  ['Add funds by UPI, track both wallets, or recharge a mobile number instead of buying right now.', 'UPI से पैसे जोड़ें, दोनों वॉलेट देखें, या अभी खरीदने की बजाय मोबाइल नंबर रिचार्ज करें।', 'UPI-তে টাকা যোগ করুন, দুটি ওয়ালেটই দেখুন, বা এখনই কেনার বদলে মোবাইল নম্বর রিচার্জ করুন।'],
  ['Free to register. What it costs, what is expected, and what you are paid on.', 'पंजीकरण मुफ़्त है। क्या लागत है, क्या अपेक्षित है, और किस पर भुगतान मिलता है।', 'নিবন্ধন বিনামূল্যে। খরচ কত, কী প্রত্যাশিত, এবং কীসের ওপর পেমেন্ট পান।'],
  ['Your network', 'आपका नेटवर्क', 'আপনার নেটওয়ার্ক'],
  ['Your team and your referral link, once you are a member.', 'आपकी टीम और आपका रेफ़रल लिंक, सदस्य बनने के बाद।', 'আপনার টিম ও রেফারেল লিঙ্ক, সদস্য হওয়ার পর।'],
  ['Your account', 'आपका खाता', 'আপনার অ্যাকাউন্ট'],
  ['Rank, volume, payout details and order history in one place.', 'रैंक, वॉल्यूम, पेआउट विवरण और ऑर्डर इतिहास एक जगह।', 'র‍্যাঙ্ক, ভলিউম, পেআউট বিবরণ ও অর্ডার ইতিহাস এক জায়গায়।'],
  ['Help & policies', 'सहायता और नीतियाँ', 'সাহায্য ও নীতিমালা'],
  ['Ordering, delivery, returns and membership — answered plainly, with every policy linked below.', 'ऑर्डर, डिलीवरी, वापसी और सदस्यता — सरल भाषा में जवाब, हर नीति नीचे जुड़ी है।', 'অর্ডার, ডেলিভারি, ফেরত ও সদস্যপদ — সহজ ভাষায় উত্তর, প্রতিটি নীতি নিচে যুক্ত।'],
  ['Beauty from brands you know', 'जाने-पहचाने ब्रांड की ब्यूटी', 'পরিচিত ব্র্যান্ডের বিউটি'],
  ['Beauty brands you love,', 'ब्यूटी ब्रांड जिन्हें आप पसंद करते हैं,', 'যে বিউটি ব্র্যান্ড আপনি ভালোবাসেন,'],
  ['under one roof', 'एक ही छत के नीचे', 'এক ছাদের নিচে'],
  ['Shop makeup, skin care, body care and fragrance from brands you already trust — Lakmé, Lotus Herbals, Pond’s, Dot & Key, Himalaya and more — delivered to your door.', 'उन ब्रांड से मेकअप, स्किन केयर, बॉडी केयर और फ्रेगरेंस खरीदें जिन पर आप पहले से भरोसा करते हैं — Lakmé, Lotus Herbals, Pond’s, Dot & Key, Himalaya और बहुत कुछ — आपके दरवाज़े तक डिलीवर।', 'যে ব্র্যান্ডগুলিতে আপনি আগে থেকেই ভরসা করেন — Lakmé, Lotus Herbals, Pond’s, Dot & Key, Himalaya এবং আরও অনেক — সেগুলির মেকআপ, স্কিন কেয়ার, বডি কেয়ার ও ফ্র্যাগরেন্স কিনুন, আপনার দরজায় পৌঁছে যাবে।'],
  ['Log in to shop from your wallet and follow your team.', 'अपने वॉलेट से खरीदारी करने और अपनी टीम को देखने के लिए लॉग इन करें।', 'আপনার ওয়ালেট থেকে কেনাকাটা করতে ও আপনার টিম দেখতে লগ ইন করুন।'],
  ['Free to register. No registration fee.', 'पंजीकरण मुफ़्त। कोई पंजीकरण शुल्क नहीं।', 'নিবন্ধন বিনামূল্যে। কোনো নিবন্ধন ফি নেই।'],
  ['We will send a one-time code to your registered email address.', 'हम आपके पंजीकृत ईमेल पते पर एक वन-टाइम कोड भेजेंगे।', 'আমরা আপনার নিবন্ধিত ইমেইল ঠিকানায় একটি ওয়ান-টাইম কোড পাঠাব।'],
  ['Real people, reachable during business hours. Every complaint gets an acknowledgement.', 'असली लोग, कारोबारी घंटों में उपलब्ध। हर शिकायत को पावती मिलती है।', 'আসল মানুষ, ব্যবসার সময়ে পাওয়া যায়। প্রতিটি অভিযোগের স্বীকৃতি দেওয়া হয়।'],
  ['Orders, delivery, returns and wallet questions.', 'ऑर्डर, डिलीवरी, वापसी और वॉलेट से जुड़े सवाल।', 'অর্ডার, ডেলিভারি, ফেরত ও ওয়ালেট সংক্রান্ত প্রশ্ন।'],
  ['If customer care has not resolved your issue, escalate here.', 'यदि ग्राहक सेवा ने आपकी समस्या हल नहीं की, तो यहाँ शिकायत बढ़ाएँ।', 'গ্রাহক সেবা সমস্যার সমাধান না করলে এখানে জানান।'],
  ['Acknowledged within 48 hours and resolved within one month, as required by the Consumer Protection (E-Commerce) Rules, 2020.', 'उपभोक्ता संरक्षण (ई-कॉमर्स) नियम, 2020 की आवश्यकता के अनुसार 48 घंटे में पावती और एक महीने में समाधान।', 'ভোক্তা সুরক্ষা (ই-কমার্স) বিধি, ২০২০ অনুযায়ী ৪৮ ঘণ্টার মধ্যে স্বীকৃতি ও এক মাসের মধ্যে সমাধান।'],
  ['Ask a question or raise a complaint. You get a reference number, and we acknowledge it within 48 hours. Members can also do this from the Support tab in their account, where the replies appear.', 'कोई सवाल पूछें या शिकायत दर्ज करें। आपको एक संदर्भ नंबर मिलता है, और हम 48 घंटे में पावती देते हैं। सदस्य अपने खाते के सपोर्ट टैब से भी ऐसा कर सकते हैं, जहाँ जवाब दिखते हैं।', 'প্রশ্ন করুন বা অভিযোগ জানান। আপনি একটি রেফারেন্স নম্বর পাবেন এবং আমরা ৪৮ ঘণ্টার মধ্যে স্বীকৃতি দিই। সদস্যরা তাঁদের অ্যাকাউন্টের সাপোর্ট ট্যাব থেকেও এটি করতে পারেন, যেখানে উত্তর দেখা যায়।'],
  ['Skin care guidance, ingredient explainers and product updates from Majestic Cart.', 'Majestic Cart से स्किन केयर मार्गदर्शन, सामग्री की जानकारी और उत्पाद अपडेट।', 'Majestic Cart থেকে স্কিন কেয়ার নির্দেশনা, উপকরণের ব্যাখ্যা ও পণ্য আপডেট।'],
  ['Nothing published yet. Check back soon.', 'अभी कुछ प्रकाशित नहीं हुआ। जल्द दोबारा देखें।', 'এখনও কিছু প্রকাশিত হয়নি। শীঘ্রই আবার দেখুন।'],
  ['Every order placed here is on {name}’s recommendation. Wallet, delivery and returns work exactly as they do anywhere else on the site.', 'यहाँ दिया गया हर ऑर्डर {name} की सिफ़ारिश पर है। वॉलेट, डिलीवरी और वापसी साइट पर बाकी जगह की तरह ही काम करते हैं।', 'এখানে দেওয়া প্রতিটি অর্ডার {name}-এর সুপারিশে। ওয়ালেট, ডেলিভারি ও ফেরত সাইটের অন্য যেকোনো জায়গার মতোই কাজ করে।'],
  ['Want to sell like {name}? See how to join →', '{name} की तरह बेचना चाहते हैं? जुड़ने का तरीका देखें →', '{name}-এর মতো বিক্রি করতে চান? কীভাবে যোগ দেবেন দেখুন →'],
  ['The full range', 'पूरी रेंज', 'পুরো সংগ্রহ'],
  ['The full {name} range, sold direct through Majestic Cart.', 'पूरी {name} रेंज, Majestic Cart के ज़रिए सीधे बिक्री के लिए।', 'পুরো {name} সংগ্রহ, Majestic Cart-এর মাধ্যমে সরাসরি বিক্রি।'],
  ['{name} products are on their way', '{name} के उत्पाद जल्द आ रहे हैं', '{name}-এর পণ্য শীঘ্রই আসছে'],
  ['We carry {name}, but nothing is listed just yet. Have a look at the rest of the range.', 'हमारे पास {name} है, लेकिन अभी कुछ सूचीबद्ध नहीं है। बाकी रेंज देखें।', 'আমাদের কাছে {name} আছে, কিন্তু এখনও কিছু তালিকাভুক্ত হয়নি। বাকি সংগ্রহটি দেখুন।'],
  ['Nothing here yet. Have a look at what is in stock.', 'अभी यहाँ कुछ नहीं है। देखें कि स्टॉक में क्या है।', 'এখনও এখানে কিছু নেই। স্টকে কী আছে দেখুন।'],
  ['GST and delivery are calculated at checkout, once the delivery address is chosen. Prices shown are from when each item was added and are confirmed again before you pay.', 'GST और डिलीवरी की गणना चेकआउट पर होती है, जब डिलीवरी का पता चुन लिया जाता है। दिखाई गई कीमतें तब की हैं जब हर आइटम जोड़ा गया था और भुगतान से पहले दोबारा पक्की की जाती हैं।', 'GST ও ডেলিভারি চেকআউটে হিসাব হয়, ডেলিভারির ঠিকানা বেছে নেওয়ার পর। দেখানো দাম প্রতিটি আইটেম যোগ করার সময়কার এবং পেমেন্টের আগে আবার নিশ্চিত করা হয়।'],
  ['Orders are paid from your shopping wallet. There is no card payment on this site.', 'ऑर्डर का भुगतान आपके शॉपिंग वॉलेट से होता है। इस साइट पर कार्ड भुगतान नहीं है।', 'অর্ডারের পেমেন্ট আপনার শপিং ওয়ালেট থেকে হয়। এই সাইটে কার্ড পেমেন্ট নেই।'],
  ['Income wallet: {amount} — withdrawable to your bank, not spendable here.', 'इनकम वॉलेट: {amount} — आपके बैंक में निकाला जा सकता है, यहाँ खर्च नहीं किया जा सकता।', 'ইনকাম ওয়ালেট: {amount} — আপনার ব্যাংকে তোলা যায়, এখানে খরচ করা যায় না।'],
  ['Welcome to Majestic Cart!', 'Majestic Cart में आपका स्वागत है!', 'Majestic Cart-এ স্বাগতম!'],
];
