import { ReportDefinition, ReportDefinitionSchema } from './compiler';

/**
 * The shipped report library.
 *
 * Every one of these is data, not code. The client can edit any of them from
 * the admin console, clone one as a starting point, or build something new from
 * the same catalog — without a deploy.
 *
 * They are validated at module load, so a typo in a preset fails at boot rather
 * than when someone opens the report.
 */

const define = (d: ReportDefinition): ReportDefinition => d;

/* ------------------------------------------------------------- finance */

export const FINANCE_REPORTS: ReportDefinition[] = [
  define({
    key: 'revenue_trend',
    name: 'Revenue and volume trend',
    description: 'Monthly revenue, business volume and order count.',
    dataset: 'orders',
    dimensions: ['placedAt'],
    bucket: 'month',
    measures: ['revenue', 'bv', 'orderCount', 'aov'],
    filters: [],
    limit: 36,
    chartType: 'line',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'commission_liability',
    name: 'Commission liability by month',
    description: 'What the plan actually paid out, split by income type. Read alongside revenue to watch the payout ratio.',
    dataset: 'commission',
    dimensions: ['paidAt', 'type'],
    bucket: 'month',
    measures: ['amount', 'legCount', 'earnerCount'],
    filters: [],
    limit: 300,
    chartType: 'stackedBar',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'wallet_float',
    name: 'Wallet float by rank',
    description: 'Member money held on the platform. This is a liability against goods not yet delivered, not revenue.',
    dataset: 'members',
    dimensions: ['rank'],
    measures: ['memberCount', 'shoppingBalance', 'incomeBalance', 'walletFloat'],
    filters: [{ dimension: 'memberStatus', op: 'eq', value: 'ACTIVE' }],
    limit: 20,
    chartType: 'bar',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'gst_by_month',
    name: 'GST collected by month',
    description: 'Tax component of delivered orders, for the monthly return.',
    dataset: 'orders',
    dimensions: ['placedAt'],
    bucket: 'month',
    measures: ['netOfGst', 'gst', 'revenue', 'orderCount'],
    filters: [{ dimension: 'status', op: 'eq', value: 'DELIVERED' }],
    limit: 36,
    chartType: 'table',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'gst_by_state',
    name: 'GST by state',
    description: 'Place-of-supply split. Needed once turnover crosses the registration threshold in more than one state.',
    dataset: 'orders',
    dimensions: ['state'],
    measures: ['netOfGst', 'gst', 'revenue', 'orderCount'],
    filters: [{ dimension: 'status', op: 'eq', value: 'DELIVERED' }],
    sort: { field: 'revenue', direction: 'desc' },
    limit: 40,
    chartType: 'table',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'withdrawal_register',
    name: 'Withdrawal and deduction register',
    description: 'Payouts with the deduction withheld, by month. The basis for the TDS filing.',
    dataset: 'withdrawals',
    dimensions: ['requestedAt', 'status'],
    bucket: 'month',
    measures: ['requested', 'deduction', 'net', 'requestCount'],
    filters: [],
    limit: 200,
    chartType: 'table',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'sku_commission_efficiency',
    name: 'Product commission efficiency',
    description: 'Revenue left outside the BV pool, per SKU. A low or negative figure means the product cannot fund its own payout.',
    dataset: 'order_items',
    dimensions: ['sku', 'productName'],
    measures: ['units', 'revenue', 'bv', 'marginPool'],
    filters: [],
    sort: { field: 'marginPool', direction: 'asc' },
    limit: 200,
    chartType: 'table',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'ledger_movement',
    name: 'Ledger movement by category',
    description: 'Every money flow by category and month. The audit-grade view.',
    dataset: 'ledger',
    dimensions: ['postedAt', 'category', 'wallet'],
    bucket: 'month',
    measures: ['netAmount', 'amount', 'entryCount'],
    filters: [],
    limit: 1000,
    chartType: 'table',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
];

/* ---------------------------------------------------------- compliance */

export const COMPLIANCE_REPORTS: ReportDefinition[] = [
  define({
    key: 'recruitment_vs_retail',
    name: 'Recruitment versus retail income',
    description:
      'Income paid on first orders and joining, against income from repeat sales. If the recruitment line outgrows the retail line, the plan is drifting toward the structure the Direct Selling Rules target.',
    dataset: 'commission',
    dimensions: ['paidAt', 'type'],
    bucket: 'month',
    measures: ['amount', 'legCount'],
    filters: [],
    limit: 300,
    chartType: 'area',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'income_distribution',
    name: 'Income distribution',
    description:
      'Median, 90th percentile and average commission per earner. In most direct-selling plans the median is close to zero, and this is the honest basis for any income claim the company or its members make.',
    dataset: 'commission',
    dimensions: ['paidAt'],
    bucket: 'month',
    measures: ['medianPerEarner', 'p90', 'avgPerLeg', 'earnerCount', 'amount'],
    filters: [],
    limit: 36,
    chartType: 'line',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'income_by_rank',
    name: 'Income concentration by rank',
    description: 'How much of total payout each rank absorbs, and how many members share it.',
    dataset: 'commission',
    dimensions: ['rank'],
    measures: ['amount', 'earnerCount', 'medianPerEarner', 'p90'],
    filters: [],
    sort: { field: 'amount', direction: 'desc' },
    limit: 20,
    chartType: 'bar',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'repurchase_histogram',
    name: 'Monthly purchase distribution',
    description:
      'Members bucketed by how much they bought this month. A hard spike at exactly the repurchase target means people are buying to unlock withdrawals rather than because they want the product — inventory loading, and invisible in an average.',
    dataset: 'monthly_volume',
    dimensions: ['selfBvBand'],
    measures: ['memberCount', 'selfBv'],
    filters: [],
    sort: { field: 'selfBvBand', direction: 'asc' },
    limit: 100,
    chartType: 'histogram',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'dormant_with_balance',
    name: 'Dormant members holding money',
    description: 'Active accounts with wallet money and no recent login. Unclaimed member funds are a liability that grows quietly.',
    dataset: 'members',
    dimensions: ['memberCode', 'memberName', 'state', 'lastLoginAt'],
    measures: ['shoppingBalance', 'incomeBalance', 'walletFloat'],
    filters: [{ dimension: 'memberStatus', op: 'eq', value: 'ACTIVE' }],
    sort: { field: 'walletFloat', direction: 'desc' },
    limit: 500,
    chartType: 'table',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'withdrawal_rejections',
    name: 'Withdrawal rejection pattern',
    description: 'Rejections by month. A rising rate usually means the payout rules are unclear to members, not that members are at fault.',
    dataset: 'withdrawals',
    dimensions: ['requestedAt', 'status'],
    bucket: 'month',
    measures: ['requestCount', 'requested'],
    filters: [],
    limit: 200,
    chartType: 'stackedBar',
    audience: ['ADMIN', 'SUPPORT'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'rounding_reconciliation',
    name: 'Rounding dust reconciliation',
    description: 'Sub-paise remainder dropped by commission rounding. Should track predictably; a jump means a plan change altered the arithmetic.',
    dataset: 'commission',
    dimensions: ['paidAt'],
    bucket: 'month',
    measures: ['roundingDust', 'legCount', 'amount'],
    filters: [],
    limit: 36,
    chartType: 'table',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
];

/* -------------------------------------------------------------- growth */

export const GROWTH_REPORTS: ReportDefinition[] = [
  define({
    key: 'signup_cohorts',
    name: 'Signups by month',
    description: 'New members per month, split by rank reached.',
    dataset: 'members',
    dimensions: ['joinedAt', 'rank'],
    bucket: 'month',
    measures: ['memberCount', 'groupBv', 'selfBv'],
    filters: [],
    limit: 300,
    chartType: 'stackedBar',
    audience: ['ADMIN'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'sponsor_leaderboard',
    name: 'Sponsor leaderboard',
    description: 'Who is actually recruiting, and whether their recruits buy anything.',
    dataset: 'members',
    dimensions: ['sponsorCode'],
    measures: ['memberCount', 'selfBv', 'walletFloat'],
    filters: [],
    sort: { field: 'memberCount', direction: 'desc' },
    limit: 100,
    chartType: 'table',
    audience: ['ADMIN'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'geographic_spread',
    name: 'Revenue by state and city',
    description: 'Where the orders actually ship. Drives stocking and delivery partner decisions.',
    dataset: 'orders',
    dimensions: ['state', 'city'],
    measures: ['revenue', 'orderCount', 'buyerCount', 'bv'],
    filters: [],
    sort: { field: 'revenue', direction: 'desc' },
    limit: 300,
    chartType: 'heatmap',
    audience: ['ADMIN'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'first_order_conversion',
    name: 'First orders versus repeat orders',
    description: 'How much of the business is new members buying once, against members who keep buying.',
    dataset: 'orders',
    dimensions: ['placedAt', 'isFirstPurchase'],
    bucket: 'month',
    measures: ['orderCount', 'revenue', 'bv', 'aov'],
    filters: [],
    limit: 200,
    chartType: 'stackedBar',
    audience: ['ADMIN'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'category_mix',
    name: 'Category mix over time',
    description: 'What members actually buy, month by month.',
    dataset: 'order_items',
    dimensions: ['placedAt', 'category'],
    bucket: 'month',
    measures: ['revenue', 'units', 'bv'],
    filters: [],
    limit: 400,
    chartType: 'area',
    audience: ['ADMIN'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'depth_distribution',
    name: 'Network depth distribution',
    description: 'How many members sit at each level of the tree. A very deep, very thin tree is a recruitment chain, not a sales force.',
    dataset: 'members',
    dimensions: ['depth'],
    measures: ['memberCount', 'selfBv', 'groupBv'],
    filters: [],
    sort: { field: 'depth', direction: 'asc' },
    limit: 100,
    chartType: 'bar',
    audience: ['ADMIN'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'top_products',
    name: 'Best selling products',
    description: 'Units and revenue per SKU.',
    dataset: 'order_items',
    dimensions: ['sku', 'productName', 'category'],
    measures: ['units', 'revenue', 'bv'],
    filters: [],
    sort: { field: 'revenue', direction: 'desc' },
    limit: 100,
    chartType: 'bar',
    audience: ['ADMIN'],
    scope: 'GLOBAL',
  }),
];

/* ---------------------------------------------------------- operations */

export const OPERATIONS_REPORTS: ReportDefinition[] = [
  define({
    key: 'recharge_sla',
    name: 'Recharge verification SLA',
    description:
      'Minutes from a member submitting payment proof to an admin deciding. Manual verification is the one cost that scales linearly with member count, so this is the number to watch as the client grows.',
    dataset: 'recharges',
    dimensions: ['submittedAt', 'status'],
    bucket: 'day',
    measures: ['requestCount', 'avgReviewMinutes', 'claimed', 'credited'],
    filters: [],
    limit: 400,
    chartType: 'line',
    audience: ['ADMIN', 'SUPPORT'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'recharge_discrepancy',
    name: 'Claimed versus credited',
    description: 'Where the amount a member typed differed from the bank statement. A persistent gap points at a confusing recharge screen.',
    dataset: 'recharges',
    dimensions: ['submittedAt'],
    bucket: 'month',
    measures: ['claimed', 'credited', 'discrepancy', 'requestCount'],
    filters: [{ dimension: 'status', op: 'eq', value: 'APPROVED' }],
    limit: 36,
    chartType: 'table',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'flagged_recharges',
    name: 'Flagged recharges',
    description: 'Requests the fraud rules flagged, and what the admin decided.',
    dataset: 'recharges',
    dimensions: ['submittedAt', 'status', 'memberCode', 'memberName'],
    bucket: 'day',
    measures: ['requestCount', 'claimed'],
    filters: [{ dimension: 'hasFlags', op: 'eq', value: 'true' }],
    sort: { field: 'claimed', direction: 'desc' },
    limit: 500,
    chartType: 'table',
    audience: ['ADMIN'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'fulfilment_sla',
    name: 'Order fulfilment SLA',
    description: 'Average hours from order to delivery, by month and state.',
    dataset: 'orders',
    dimensions: ['placedAt', 'state'],
    bucket: 'month',
    measures: ['orderCount', 'fulfilHours', 'revenue'],
    filters: [{ dimension: 'status', op: 'eq', value: 'DELIVERED' }],
    limit: 400,
    chartType: 'table',
    audience: ['ADMIN', 'SUPPORT'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'payout_settlement',
    name: 'Payout settlement speed',
    description: 'Hours from withdrawal request to money sent. Slow payouts are the fastest way to lose a productive member.',
    dataset: 'withdrawals',
    dimensions: ['requestedAt'],
    bucket: 'week',
    measures: ['requestCount', 'avgSettleHours', 'net'],
    filters: [{ dimension: 'status', op: 'eq', value: 'PAID' }],
    limit: 120,
    chartType: 'line',
    audience: ['ADMIN', 'FINANCE'],
    scope: 'GLOBAL',
  }),
  define({
    key: 'alert_resolution',
    name: 'Security alert resolution',
    description: 'Alerts raised and how long they took to close, by severity.',
    dataset: 'alerts',
    dimensions: ['raisedAt', 'severity', 'type'],
    bucket: 'week',
    measures: ['alertCount', 'avgResolutionHours'],
    filters: [],
    limit: 400,
    chartType: 'table',
    audience: ['ADMIN'],
    scope: 'GLOBAL',
  }),
];

/* ------------------------------------------------------ member-facing */

/**
 * Member reports run against the same catalog and the same compiler. The
 * difference is entirely in who asks: the compiler appends the downline
 * predicate for a MEMBER caller regardless of what these definitions say.
 */
export const MEMBER_REPORTS: ReportDefinition[] = [
  define({
    key: 'my_income_breakdown',
    name: 'Where my income comes from',
    description: 'Your earnings split by income type, month by month.',
    dataset: 'commission',
    dimensions: ['paidAt', 'type'],
    bucket: 'month',
    measures: ['amount', 'legCount'],
    filters: [],
    limit: 120,
    chartType: 'stackedBar',
    audience: ['MEMBER'],
    scope: 'OWN_ROWS',
  }),
  define({
    key: 'my_team_growth',
    name: 'My team growth',
    description: 'New members in your downline, month by month.',
    dataset: 'members',
    dimensions: ['joinedAt', 'rank'],
    bucket: 'month',
    measures: ['memberCount', 'groupBv'],
    filters: [],
    limit: 120,
    chartType: 'bar',
    audience: ['MEMBER'],
    scope: 'OWN_DOWNLINE',
  }),
  define({
    key: 'my_team_volume',
    name: 'My team volume',
    description: 'What your downline is buying, month by month.',
    dataset: 'orders',
    dimensions: ['placedAt'],
    bucket: 'month',
    measures: ['revenue', 'bv', 'orderCount', 'buyerCount'],
    filters: [],
    limit: 120,
    chartType: 'line',
    audience: ['MEMBER'],
    scope: 'OWN_DOWNLINE',
  }),
  define({
    key: 'my_purchases',
    name: 'My purchase history',
    description: 'What you have bought, by category.',
    dataset: 'order_items',
    dimensions: ['placedAt', 'category'],
    bucket: 'month',
    measures: ['revenue', 'units', 'bv'],
    filters: [],
    limit: 120,
    chartType: 'area',
    audience: ['MEMBER'],
    scope: 'OWN_ROWS',
  }),
  define({
    key: 'my_wallet_statement',
    name: 'My wallet statement',
    description: 'Every movement in and out of your wallets.',
    dataset: 'ledger',
    dimensions: ['postedAt', 'category', 'wallet', 'direction'],
    bucket: 'day',
    measures: ['netAmount', 'entryCount'],
    filters: [],
    limit: 500,
    chartType: 'table',
    audience: ['MEMBER'],
    scope: 'OWN_ROWS',
  }),
];

export const ALL_PRESETS: ReportDefinition[] = [
  ...FINANCE_REPORTS,
  ...COMPLIANCE_REPORTS,
  ...GROWTH_REPORTS,
  ...OPERATIONS_REPORTS,
  ...MEMBER_REPORTS,
];

/**
 * Validate every preset at module load. A typo in a catalog key here should
 * break the boot, not the first admin who opens that report.
 */
export function validatePresets(): ReportDefinition[] {
  return ALL_PRESETS.map((preset) => {
    const result = ReportDefinitionSchema.safeParse(preset);
    if (!result.success) {
      throw new Error(`Preset "${preset.key}" is invalid: ${JSON.stringify(result.error.issues)}`);
    }
    return result.data;
  });
}

export const PRESET_GROUPS = [
  { key: 'finance', label: 'Finance', reports: FINANCE_REPORTS },
  { key: 'compliance', label: 'Compliance', reports: COMPLIANCE_REPORTS },
  { key: 'growth', label: 'Growth', reports: GROWTH_REPORTS },
  { key: 'operations', label: 'Operations', reports: OPERATIONS_REPORTS },
  { key: 'member', label: 'Member facing', reports: MEMBER_REPORTS },
];
